services:
  dennys:
    build: .
    image: dennys:dev
    container_name: dennys-container
    ports:
      - "127.0.0.1:9292:9292"
    env_file: .env
    environment:
      - LBLCS_JDBC_URL=${LBLCS_JDBC_URL}
      - LBLCS_JDBC_PW=${LBLCS_JDBC_PW}
      - RIOT_API_TOKEN=${RIOT_API_TOKEN}
      - RIOT_USE_STUBS=${RIOT_USE_STUBS}
      - LOG_PATH=/app/logs
    volumes:
      - ./logs:/app/logs  # Bind mount for logs
    logging:
        driver: json-file
        options:
          max-size: "10m"
          max-file: "5"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    container_name: postgres-dennys
    ports:
      - "127.0.0.1:5432:5432"
    user: postgres
    environment:
      - POSTGRES_PASSWORD=dev
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./build/resources/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s 
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4:9.0
    container_name: pgadmin-dennys
    ports: 
      - "127.0.0.1:8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@dev.com
      - PGADMIN_DEFAULT_PASSWORD=dev
      - PGADMIN_DISABLE_POSTFIX=true
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin-data:
