services:
  dennys:
    build: 
      context: .
      dockerfile: docker/Dockerfile
      target: app
    image: dennys:local
    container_name: dennys-container
    ports:
      - "127.0.0.1:9292:9292"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    container_name: dennys-db
    ports:
      - "127.0.0.1:5432:5432"
    user: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      # DB Init Scripts
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s 
      timeout: 10s
      retries: 3

  swagger-editor:
    container_name: swagger
    image: swaggerapi/swagger-editor
    ports: 
      - "127.0.0.1:80:8080"
    volumes:
      - ./docker/swaggerEditor/openapi.yaml:/spec/openapi.yaml
    environment:
      SWAGGER_FILE: /spec/openapi.yaml

