services:
  dennys:
    build: .
    image: dennys:latest
    container_name: dennys-container
    ports:
      - "9292:9292"
    networks:
      - rabbitmq.docker

networks:
  rabbitmq.docker:
    name: rabbitmq.docker
    external: true
