database.url=jdbc:postgresql://db:5432/postgres?user=postgres&prepareThreshold=0
database.password=admin
riot.useStubs=true
riot.providerId=1
cookie.expiration=3600
cookie.secure=true
cors.url=
cors.scheme=
logging.cid=CID