database.url=jdbc:postgresql://db:5432/postgres?user=postgres&prepareThreshold=0
database.password=admin
database.logoBucketName=/logos
riot.useStubs=true
riot.providerId=1
cookie.expiration=3600
cookie.secure=true
api.cors=