START TRANSACTION;
DROP SCHEMA IF EXISTS dennys CASCADE;

CREATE SCHEMA dennys;

SET SEARCH_PATH = dennys;

CREATE TABLE metadata (
  riot_provider_id INTEGER NOT NULL,
  logo_bucket_name TEXT NOT NULL
);

CREATE TABLE events (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT DEFAULT '' NOT NULL,
  riot_tournament_id INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL
);

CREATE TABLE teams (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  logo_name TEXT,
  event_id INTEGER REFERENCES events(id)
);

CREATE TABLE players (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  event_id INTEGER REFERENCES events(id),
  team_id INTEGER REFERENCES teams(id)
);

CREATE TABLE player_to_teams (
  player_id INTEGER REFERENCES players(id),
  team_id INTEGER REFERENCES teams(id),
  event_id INTEGER REFERENCES events(id),
  PRIMARY KEY (player_id, event_id)
);

CREATE TABLE riot_accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  riot_puuid TEXT UNIQUE NOT NULL
);

CREATE TABLE riot_account_to_player (
  player_id INTEGER REFERENCES players(id),
  riot_account_id INTEGER REFERENCES riot_accounts(id),
  PRIMARY KEY (player_id, riot_account_id)
);

CREATE TABLE series (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id INTEGER REFERENCES events(id),
  games_to_win INTEGER NOT NULL
);

CREATE TABLE series_participants (
  team_id INTEGER REFERENCES teams(id),
  series_id INTEGER REFERENCES series(id),
  PRIMARY KEY (team_id, series_id)
);

CREATE TABLE series_results (
  series_id INTEGER REFERENCES series(id) PRIMARY KEY,
  winner INTEGER REFERENCES teams(id),
  loser INTEGER REFERENCES teams(id)
);

CREATE TABLE games (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shortcode TEXT NOT NULL,
  blue_team INTEGER REFERENCES teams(id),
  red_team INTEGER REFERENCES teams(id),
  series_id INTEGER REFERENCES series(id)
);

CREATE TABLE games_results (
  game_id INTEGER REFERENCES games(id) PRIMARY KEY,
  winner INTEGER REFERENCES teams(id),
  loser INTEGER REFERENCES teams(id)
);

CREATE TABLE player_champ_selects (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  champion_name TEXT NOT NULL,
  champion_id INTEGER NOT NULL,
  summoner1_id INTEGER NOT NULL,
  summoner2_id INTEGER NOT NULL,
  keystone_rune_id INTEGER NOT NULL,
  primary_rune1_id INTEGER NOT NULL,
  primary_rune2_id INTEGER NOT NULL,
  primary_rune3_id INTEGER NOT NULL,
  secondary_rune1_id INTEGER NOT NULL,
  secondary_rune2_id INTEGER NOT NULL,
  statshard1_id INTEGER NOT NULL,
  statshard2_id INTEGER NOT NULL,
  statshard3_id INTEGER NOT NULL
);

CREATE TABLE player_inventories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item0_id INTEGER NOT NULL,
  item1_id INTEGER NOT NULL,
  item2_id INTEGER NOT NULL,
  item3_id INTEGER NOT NULL,
  item4_id INTEGER NOT NULL,
  item5_id INTEGER NOT NULL,
  trinket_id INTEGER NOT NULL
);

CREATE TABLE player_combats (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kills INTEGER NOT NULL,
  deaths INTEGER NOT NULL,
  assists INTEGER NOT NULL,
  damage_to_champs INTEGER NOT NULL,
  healing_on_allies INTEGER NOT NULL,
  damage_taken_from_champs INTEGER NOT NULL,
  team_kills INTEGER NOT NULL
);

CREATE TABLE player_vision (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vision_score INTEGER NOT NULL,
  pinks_purchased INTEGER NOT NULL,
  pinks_placed INTEGER NOT NULL,
  wards_placed INTEGER NOT NULL,
  wards_destroyed INTEGER NOT NULL
);

CREATE TABLE player_pings (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  on_my_way_count INTEGER NOT NULL,
  enemy_missing_count INTEGER NOT NULL,
  assist_me_count INTEGER NOT NULL,
  get_back_count INTEGER NOT NULL,
  enemy_vision_count INTEGER NOT NULL,
  all_in_count INTEGER NOT NULL,
  need_vision_count INTEGER NOT NULL,
  push_count INTEGER NOT NULL,
  vision_cleared_count INTEGER NOT NULL
);

CREATE TABLE player_farming (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  total_gold INTEGER NOT NULL,
  creep_score INTEGER NOT NULL,
  level INTEGER NOT NULL
);

CREATE TABLE player_game_facts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  riot_account_id INTEGER REFERENCES riot_accounts(id),
  side INTEGER NOT NULL,
  shortcode TEXT NOT NULL,
  player_champ_select_id INTEGER REFERENCES player_champ_selects (id),
  player_inventories_id INTEGER REFERENCES player_inventories(id),
  player_combats_id INTEGER REFERENCES player_combats(id),
  player_vision_id INTEGER REFERENCES player_vision(id),
  player_pings_id INTEGER REFERENCES player_pings(id),
  player_farming_id INTEGER REFERENCES player_farming(id)
);

CREATE TABLE player_audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  player_id INTEGER REFERENCES players(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  origin TEXT NOT NULL
);

CREATE TABLE riot_accounts_audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  riot_account_id INTEGER REFERENCES riot_accounts(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  origin TEXT NOT NULL
);

CREATE TABLE team_audit_logs (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  team_id INTEGER REFERENCES teams(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  origin TEXT NOT NULL
);

CREATE TABLE event_audit_log (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  event_id INTEGER REFERENCES events(id),
  action TEXT NOT NULL,
  message TEXT NOT NULL,
  origin TEXT NOT NULL
);

COMMIT;