START TRANSACTION;
SET SEARCH_PATH = dennys;

ALTER TABLE riot_accounts 
  ADD COLUMN player_id INTEGER
  REFERENCES players(id);

ALTER TABLE players
  DROP COLUMN main_account_id;

DROP TABLE IF EXISTS riot_accounts_to_player;

CREATE TABLE IF NOT EXISTS players_to_team (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id  INTEGER NOT NULL,
  team_id    INTEGER NOT NULL,

  CONSTRAINT players_to_team_player_fkey
    FOREIGN KEY (player_id) REFERENCES players(id)
    ON UPDATE NO ACTION ON DELETE CASCADE,

  CONSTRAINT players_to_team_team_fkey
    FOREIGN KEY (team_id) REFERENCES teams(id)
    ON UPDATE NO ACTION ON DELETE CASCADE,

  CONSTRAINT players_to_team_unique UNIQUE (player_id, team_id)
);

CREATE TABLE IF NOT EXISTS players_to_event (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  player_id  INTEGER NOT NULL,
  event_id   INTEGER NOT NULL,

  CONSTRAINT players_to_event_player_fkey
    FOREIGN KEY (player_id) REFERENCES players(id)
    ON UPDATE NO ACTION ON DELETE CASCADE,

  CONSTRAINT players_to_event_event_fkey
    FOREIGN KEY (event_id) REFERENCES events(id)
    ON UPDATE NO ACTION ON DELETE CASCADE,

  CONSTRAINT players_to_event_unique UNIQUE (player_id, event_id)
);

DROP TABLE IF EXISTS player_to_teams;

COMMIT;
