START TRANSACTION;
SET search_path = dennys;

create table users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  roles TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

create table access_tokens (
  token_hash TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id),
  scopes TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

create table sessions (
  id UUID PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  expires_at TIMESTAMPTZ NOT NULL
);

COMMIT;
