START TRANSACTION;
SET search_path = dennys;

create table users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  roles TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

create table personal_access_tokens (
  token TEXT PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  scopes TEXT NOT NULL
);

create table sessions (
  id INTEGER PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  expires_at TIMESTAMPTZ NOT NULL,
  csrf_token INTEGER,
  user_agent TEXT NOT NULL,
  ip_address TEXT NOT NULL
);

COMMIT;
