START TRANSACTION;
SET SEARCH_PATH = dennys;

ALTER TABLE events
  ADD COLUMN stages TEXT[] DEFAULT ARRAY['REGULAR_SEASON'] NOT NULL;

ALTER TABLE series
  ADD COLUMN stage TEXT DEFAULT 'REGULAR_SEASON' NOT NULL;

COMMIT;
