START TRANSACTION;
SET search_path = dennys;

create table users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password_hash VARCHAR NOT NULL,
  roles VARCHAR NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

create table access_tokens (
  token_hash VARCHAR PRIMARY KEY,
  name VARCHAR NOT NULL,
  user_id INTEGER REFERENCES users(id),
  scopes VARCHAR NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

create table sessions (
  id UUID PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  expires_at TIMESTAMPTZ NOT NULL
);

COMMIT;
