START TRANSACTION;
SET SEARCH_PATH = dennys;

ALTER TABLE events
  ADD COLUMN stages VARCHAR[] DEFAULT ARRAY['REGULAR_SEASON'] NOT NULL;

ALTER TABLE series
  ADD COLUMN stage VARCHAR DEFAULT 'REGULAR_SEASON' NOT NULL;

COMMIT;
