START TRANSACTION;
SET search_path = dennys;

DROP TRIGGER IF EXISTS set_game_number ON games;
DROP FUNCTION IF EXISTS assign_game_number();

ALTER TABLE game_results DROP CONSTRAINT game_results_game_id_fkey;

ALTER TABLE games RENAME TO tournament_codes;
ALTER TABLE tournament_codes DROP COLUMN number;
ALTER TABLE tournament_codes ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT now();

ALTER INDEX games_pkey RENAME TO tournament_codes_pkey;
ALTER INDEX games_shortcode_key RENAME TO tournament_codes_shortcode_key;
ALTER SEQUENCE games_id_seq RENAME TO tournament_codes_id_seq;
ALTER TABLE tournament_codes RENAME CONSTRAINT games_blue_team_id_fkey TO tournament_codes_blue_team_id_fkey;
ALTER TABLE tournament_codes RENAME CONSTRAINT games_red_team_id_fkey TO tournament_codes_red_team_id_fkey;
ALTER TABLE tournament_codes RENAME CONSTRAINT games_series_id_fkey TO tournament_codes_series_id_fkey;

CREATE TABLE games (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  series_id          INTEGER NOT NULL REFERENCES series(id),
  tournament_code_id INTEGER REFERENCES tournament_codes(id),
  riot_match_id      TEXT UNIQUE,
  number             INTEGER NOT NULL,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE game_results
  ADD CONSTRAINT game_results_game_id_fkey FOREIGN KEY (game_id) REFERENCES games(id);

COMMIT;
