/*
 * This file is generated by jOOQ.
 */
package lblcs.enums


import lblcs.Dennys

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class LolSide(@get:JvmName("literal") public val literal: String) : EnumType {
    BLUE("BLUE"),
    RED("RED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Dennys.DENNYS
    override fun getName(): String = "lol_side"
    override fun getLiteral(): String = literal
}
