/*
 * This file is generated by jOOQ.
 */
package lblcs.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import lblcs.Dennys
import lblcs.keys.EVENT_AUDIT_LOG_PKEY
import lblcs.keys.EVENT_AUDIT_LOG__EVENT_AUDIT_LOG_EVENT_ID_FKEY
import lblcs.tables.Events.EventsPath
import lblcs.tables.records.EventAuditLogRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EventAuditLog(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, EventAuditLogRecord>?,
    parentPath: InverseForeignKey<out Record, EventAuditLogRecord>?,
    aliased: Table<EventAuditLogRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<EventAuditLogRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.event_audit_log</code>
         */
        val EVENT_AUDIT_LOG: EventAuditLog = EventAuditLog()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<EventAuditLogRecord> = EventAuditLogRecord::class.java

    /**
     * The column <code>dennys.event_audit_log.id</code>.
     */
    val ID: TableField<EventAuditLogRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.event_audit_log.created_at</code>.
     */
    val CREATED_AT: TableField<EventAuditLogRecord, OffsetDateTime?> = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>dennys.event_audit_log.event_id</code>.
     */
    val EVENT_ID: TableField<EventAuditLogRecord, Int?> = createField(DSL.name("event_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.event_audit_log.action</code>.
     */
    val ACTION: TableField<EventAuditLogRecord, String?> = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.event_audit_log.message</code>.
     */
    val MESSAGE: TableField<EventAuditLogRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.event_audit_log.origin</code>.
     */
    val ORIGIN: TableField<EventAuditLogRecord, String?> = createField(DSL.name("origin"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<EventAuditLogRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<EventAuditLogRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<EventAuditLogRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.event_audit_log</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.event_audit_log</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.event_audit_log</code> table reference
     */
    constructor(): this(DSL.name("event_audit_log"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, EventAuditLogRecord>?, parentPath: InverseForeignKey<out Record, EventAuditLogRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, EVENT_AUDIT_LOG, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class EventAuditLogPath : EventAuditLog, Path<EventAuditLogRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, EventAuditLogRecord>?, parentPath: InverseForeignKey<out Record, EventAuditLogRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<EventAuditLogRecord>): super(alias, aliased)
        override fun `as`(alias: String): EventAuditLogPath = EventAuditLogPath(DSL.name(alias), this)
        override fun `as`(alias: Name): EventAuditLogPath = EventAuditLogPath(alias, this)
        override fun `as`(alias: Table<*>): EventAuditLogPath = EventAuditLogPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<EventAuditLogRecord, Int?> = super.getIdentity() as Identity<EventAuditLogRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<EventAuditLogRecord> = EVENT_AUDIT_LOG_PKEY
    override fun getReferences(): List<ForeignKey<EventAuditLogRecord, *>> = listOf(EVENT_AUDIT_LOG__EVENT_AUDIT_LOG_EVENT_ID_FKEY)

    private lateinit var _events: EventsPath

    /**
     * Get the implicit join path to the <code>dennys.events</code> table.
     */
    fun events(): EventsPath {
        if (!this::_events.isInitialized)
            _events = EventsPath(this, EVENT_AUDIT_LOG__EVENT_AUDIT_LOG_EVENT_ID_FKEY, null)

        return _events;
    }

    val events: EventsPath
        get(): EventsPath = events()
    override fun `as`(alias: String): EventAuditLog = EventAuditLog(DSL.name(alias), this)
    override fun `as`(alias: Name): EventAuditLog = EventAuditLog(alias, this)
    override fun `as`(alias: Table<*>): EventAuditLog = EventAuditLog(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): EventAuditLog = EventAuditLog(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): EventAuditLog = EventAuditLog(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): EventAuditLog = EventAuditLog(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): EventAuditLog = EventAuditLog(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): EventAuditLog = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): EventAuditLog = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): EventAuditLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): EventAuditLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): EventAuditLog = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): EventAuditLog = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): EventAuditLog = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): EventAuditLog = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): EventAuditLog = where(DSL.notExists(select))
}
