/*
 * This file is generated by jOOQ.
 */
package lblcs.tables


import kotlin.collections.Collection

import lblcs.Dennys
import lblcs.keys.PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_VISION_ID_FKEY
import lblcs.keys.PLAYER_VISION_PKEY
import lblcs.tables.PlayerGameFacts.PlayerGameFactsPath
import lblcs.tables.records.PlayerVisionRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerVision(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerVisionRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerVisionRecord>?,
    aliased: Table<PlayerVisionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerVisionRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_vision</code>
         */
        val PLAYER_VISION: PlayerVision = PlayerVision()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerVisionRecord> = PlayerVisionRecord::class.java

    /**
     * The column <code>dennys.player_vision.id</code>.
     */
    val ID: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.player_vision.vision_score</code>.
     */
    val VISION_SCORE: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("vision_score"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_vision.pinks_purchased</code>.
     */
    val PINKS_PURCHASED: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("pinks_purchased"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_vision.pinks_placed</code>.
     */
    val PINKS_PLACED: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("pinks_placed"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_vision.wards_placed</code>.
     */
    val WARDS_PLACED: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("wards_placed"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_vision.wards_destroyed</code>.
     */
    val WARDS_DESTROYED: TableField<PlayerVisionRecord, Int?> = createField(DSL.name("wards_destroyed"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerVisionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerVisionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerVisionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.player_vision</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_vision</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_vision</code> table reference
     */
    constructor(): this(DSL.name("player_vision"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerVisionRecord>?, parentPath: InverseForeignKey<out Record, PlayerVisionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_VISION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerVisionPath : PlayerVision, Path<PlayerVisionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerVisionRecord>?, parentPath: InverseForeignKey<out Record, PlayerVisionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerVisionRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerVisionPath = PlayerVisionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerVisionPath = PlayerVisionPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerVisionPath = PlayerVisionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<PlayerVisionRecord, Int?> = super.getIdentity() as Identity<PlayerVisionRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerVisionRecord> = PLAYER_VISION_PKEY

    private lateinit var _playerGameFacts: PlayerGameFactsPath

    /**
     * Get the implicit to-many join path to the
     * <code>dennys.player_game_facts</code> table
     */
    fun playerGameFacts(): PlayerGameFactsPath {
        if (!this::_playerGameFacts.isInitialized)
            _playerGameFacts = PlayerGameFactsPath(this, null, PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_VISION_ID_FKEY.inverseKey)

        return _playerGameFacts;
    }

    val playerGameFacts: PlayerGameFactsPath
        get(): PlayerGameFactsPath = playerGameFacts()
    override fun `as`(alias: String): PlayerVision = PlayerVision(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerVision = PlayerVision(alias, this)
    override fun `as`(alias: Table<*>): PlayerVision = PlayerVision(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerVision = PlayerVision(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerVision = PlayerVision(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerVision = PlayerVision(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerVision = PlayerVision(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerVision = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerVision = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerVision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerVision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerVision = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerVision = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerVision = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerVision = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerVision = where(DSL.notExists(select))
}
