/*
 * This file is generated by jOOQ.
 */
package lblcs.tables


import kotlin.collections.Collection
import kotlin.collections.List

import lblcs.Dennys
import lblcs.keys.PLAYER_TO_TEAMS_PKEY
import lblcs.keys.PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_EVENT_ID_FKEY
import lblcs.keys.PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_PLAYER_ID_FKEY
import lblcs.keys.PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_TEAM_ID_FKEY
import lblcs.tables.Events.EventsPath
import lblcs.tables.Players.PlayersPath
import lblcs.tables.Teams.TeamsPath
import lblcs.tables.records.PlayerToTeamsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerToTeams(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerToTeamsRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerToTeamsRecord>?,
    aliased: Table<PlayerToTeamsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerToTeamsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_to_teams</code>
         */
        val PLAYER_TO_TEAMS: PlayerToTeams = PlayerToTeams()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerToTeamsRecord> = PlayerToTeamsRecord::class.java

    /**
     * The column <code>dennys.player_to_teams.player_id</code>.
     */
    val PLAYER_ID: TableField<PlayerToTeamsRecord, Int?> = createField(DSL.name("player_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_to_teams.team_id</code>.
     */
    val TEAM_ID: TableField<PlayerToTeamsRecord, Int?> = createField(DSL.name("team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.player_to_teams.event_id</code>.
     */
    val EVENT_ID: TableField<PlayerToTeamsRecord, Int?> = createField(DSL.name("event_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerToTeamsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerToTeamsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerToTeamsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.player_to_teams</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_to_teams</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_to_teams</code> table reference
     */
    constructor(): this(DSL.name("player_to_teams"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerToTeamsRecord>?, parentPath: InverseForeignKey<out Record, PlayerToTeamsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_TO_TEAMS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerToTeamsPath : PlayerToTeams, Path<PlayerToTeamsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerToTeamsRecord>?, parentPath: InverseForeignKey<out Record, PlayerToTeamsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerToTeamsRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerToTeamsPath = PlayerToTeamsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerToTeamsPath = PlayerToTeamsPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerToTeamsPath = PlayerToTeamsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<PlayerToTeamsRecord> = PLAYER_TO_TEAMS_PKEY
    override fun getReferences(): List<ForeignKey<PlayerToTeamsRecord, *>> = listOf(PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_PLAYER_ID_FKEY, PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_TEAM_ID_FKEY, PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_EVENT_ID_FKEY)

    private lateinit var _players: PlayersPath

    /**
     * Get the implicit join path to the <code>dennys.players</code> table.
     */
    fun players(): PlayersPath {
        if (!this::_players.isInitialized)
            _players = PlayersPath(this, PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_PLAYER_ID_FKEY, null)

        return _players;
    }

    val players: PlayersPath
        get(): PlayersPath = players()

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table.
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_TEAM_ID_FKEY, null)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()

    private lateinit var _events: EventsPath

    /**
     * Get the implicit join path to the <code>dennys.events</code> table.
     */
    fun events(): EventsPath {
        if (!this::_events.isInitialized)
            _events = EventsPath(this, PLAYER_TO_TEAMS__PLAYER_TO_TEAMS_EVENT_ID_FKEY, null)

        return _events;
    }

    val events: EventsPath
        get(): EventsPath = events()
    override fun `as`(alias: String): PlayerToTeams = PlayerToTeams(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerToTeams = PlayerToTeams(alias, this)
    override fun `as`(alias: Table<*>): PlayerToTeams = PlayerToTeams(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerToTeams = PlayerToTeams(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerToTeams = PlayerToTeams(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerToTeams = PlayerToTeams(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerToTeams = PlayerToTeams(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerToTeams = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerToTeams = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerToTeams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerToTeams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerToTeams = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerToTeams = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerToTeams = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerToTeams = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerToTeams = where(DSL.notExists(select))
}
