/*
 * This file is generated by jOOQ.
 */
package lblcs.tables


import kotlin.collections.Collection

import lblcs.Dennys
import lblcs.keys.PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_INVENTORIES_ID_FKEY
import lblcs.keys.PLAYER_INVENTORIES_PKEY
import lblcs.tables.PlayerGameFacts.PlayerGameFactsPath
import lblcs.tables.records.PlayerInventoriesRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerInventories(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerInventoriesRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerInventoriesRecord>?,
    aliased: Table<PlayerInventoriesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerInventoriesRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_inventories</code>
         */
        val PLAYER_INVENTORIES: PlayerInventories = PlayerInventories()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerInventoriesRecord> = PlayerInventoriesRecord::class.java

    /**
     * The column <code>dennys.player_inventories.id</code>.
     */
    val ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.player_inventories.item0_id</code>.
     */
    val ITEM0_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item0_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item1_id</code>.
     */
    val ITEM1_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item1_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item2_id</code>.
     */
    val ITEM2_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item2_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item3_id</code>.
     */
    val ITEM3_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item3_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item4_id</code>.
     */
    val ITEM4_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item4_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item5_id</code>.
     */
    val ITEM5_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item5_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.trinket_id</code>.
     */
    val TRINKET_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("trinket_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.player_inventories</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_inventories</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_inventories</code> table reference
     */
    constructor(): this(DSL.name("player_inventories"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerInventoriesRecord>?, parentPath: InverseForeignKey<out Record, PlayerInventoriesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_INVENTORIES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerInventoriesPath : PlayerInventories, Path<PlayerInventoriesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerInventoriesRecord>?, parentPath: InverseForeignKey<out Record, PlayerInventoriesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerInventoriesPath = PlayerInventoriesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerInventoriesPath = PlayerInventoriesPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerInventoriesPath = PlayerInventoriesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<PlayerInventoriesRecord, Int?> = super.getIdentity() as Identity<PlayerInventoriesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerInventoriesRecord> = PLAYER_INVENTORIES_PKEY

    private lateinit var _playerGameFacts: PlayerGameFactsPath

    /**
     * Get the implicit to-many join path to the
     * <code>dennys.player_game_facts</code> table
     */
    fun playerGameFacts(): PlayerGameFactsPath {
        if (!this::_playerGameFacts.isInitialized)
            _playerGameFacts = PlayerGameFactsPath(this, null, PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_INVENTORIES_ID_FKEY.inverseKey)

        return _playerGameFacts;
    }

    val playerGameFacts: PlayerGameFactsPath
        get(): PlayerGameFactsPath = playerGameFacts()
    override fun `as`(alias: String): PlayerInventories = PlayerInventories(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerInventories = PlayerInventories(alias, this)
    override fun `as`(alias: Table<*>): PlayerInventories = PlayerInventories(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerInventories = PlayerInventories(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerInventories = PlayerInventories(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerInventories = PlayerInventories(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerInventories = PlayerInventories(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerInventories = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerInventories = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerInventories = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerInventories = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerInventories = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerInventories = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerInventories = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerInventories = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerInventories = where(DSL.notExists(select))
}
