/*
 * This file is generated by jOOQ.
 */
package lblcs.tables


import kotlin.collections.Collection
import kotlin.collections.List

import lblcs.Dennys
import lblcs.keys.SERIES_PARTICIPANTS_PKEY
import lblcs.keys.SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY
import lblcs.keys.SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY
import lblcs.tables.Series.SeriesPath
import lblcs.tables.Teams.TeamsPath
import lblcs.tables.records.SeriesParticipantsRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesParticipants(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, SeriesParticipantsRecord>?,
    parentPath: InverseForeignKey<out Record, SeriesParticipantsRecord>?,
    aliased: Table<SeriesParticipantsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<SeriesParticipantsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.series_participants</code>
         */
        val SERIES_PARTICIPANTS: SeriesParticipants = SeriesParticipants()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SeriesParticipantsRecord> = SeriesParticipantsRecord::class.java

    /**
     * The column <code>dennys.series_participants.team_id</code>.
     */
    val TEAM_ID: TableField<SeriesParticipantsRecord, Int?> = createField(DSL.name("team_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.series_participants.series_id</code>.
     */
    val SERIES_ID: TableField<SeriesParticipantsRecord, Int?> = createField(DSL.name("series_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.series_participants</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.series_participants</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.series_participants</code> table reference
     */
    constructor(): this(DSL.name("series_participants"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SeriesParticipantsRecord>?, parentPath: InverseForeignKey<out Record, SeriesParticipantsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, SERIES_PARTICIPANTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class SeriesParticipantsPath : SeriesParticipants, Path<SeriesParticipantsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, SeriesParticipantsRecord>?, parentPath: InverseForeignKey<out Record, SeriesParticipantsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>): super(alias, aliased)
        override fun `as`(alias: String): SeriesParticipantsPath = SeriesParticipantsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): SeriesParticipantsPath = SeriesParticipantsPath(alias, this)
        override fun `as`(alias: Table<*>): SeriesParticipantsPath = SeriesParticipantsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<SeriesParticipantsRecord> = SERIES_PARTICIPANTS_PKEY
    override fun getReferences(): List<ForeignKey<SeriesParticipantsRecord, *>> = listOf(SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY)

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table.
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY, null)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()

    private lateinit var _series: SeriesPath

    /**
     * Get the implicit join path to the <code>dennys.series</code> table.
     */
    fun series(): SeriesPath {
        if (!this::_series.isInitialized)
            _series = SeriesPath(this, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY, null)

        return _series;
    }

    val series: SeriesPath
        get(): SeriesPath = series()
    override fun `as`(alias: String): SeriesParticipants = SeriesParticipants(DSL.name(alias), this)
    override fun `as`(alias: Name): SeriesParticipants = SeriesParticipants(alias, this)
    override fun `as`(alias: Table<*>): SeriesParticipants = SeriesParticipants(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SeriesParticipants = SeriesParticipants(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SeriesParticipants = SeriesParticipants(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SeriesParticipants = SeriesParticipants(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): SeriesParticipants = SeriesParticipants(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): SeriesParticipants = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): SeriesParticipants = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): SeriesParticipants = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): SeriesParticipants = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): SeriesParticipants = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): SeriesParticipants = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): SeriesParticipants = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): SeriesParticipants = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): SeriesParticipants = where(DSL.notExists(select))
}
