/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant
import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.EVENTS_PKEY
import org.jooq.storage.tables.records.EventsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Events(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, EventsRecord>?,
    aliased: Table<EventsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<EventsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.events</code>
         */
        val EVENTS: Events = Events()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<EventsRecord> = EventsRecord::class.java

    /**
     * The column <code>dennys.events.id</code>.
     */
    val ID: TableField<EventsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.events.name</code>.
     */
    val NAME: TableField<EventsRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.events.description</code>.
     */
    val DESCRIPTION: TableField<EventsRecord, String?> = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "")

    /**
     * The column <code>dennys.events.riot_tournament_id</code>.
     */
    val RIOT_TOURNAMENT_ID: TableField<EventsRecord, Int?> = createField(DSL.name("riot_tournament_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.events.created_at</code>.
     */
    val CREATED_AT: TableField<EventsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>dennys.events.start_date</code>.
     */
    val START_DATE: TableField<EventsRecord, Instant?> = createField(DSL.name("start_date"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>dennys.events.end_date</code>.
     */
    val END_DATE: TableField<EventsRecord, Instant?> = createField(DSL.name("end_date"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>dennys.events.status</code>.
     */
    val STATUS: TableField<EventsRecord, String?> = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<EventsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<EventsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.events</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.events</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.events</code> table reference
     */
    constructor(): this(DSL.name("events"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, EventsRecord>): this(Internal.createPathAlias(child, key), child, key, EVENTS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<EventsRecord, Int?> = super.getIdentity() as Identity<EventsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<EventsRecord> = EVENTS_PKEY
    override fun `as`(alias: String): Events = Events(DSL.name(alias), this)
    override fun `as`(alias: Name): Events = Events(alias, this)
    override fun `as`(alias: Table<*>): Events = Events(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Events = Events(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Events = Events(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Events = Events(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, String?, String?, Int?, Instant?, Instant?, Instant?, String?> = super.fieldsRow() as Row8<Int?, String?, String?, Int?, Instant?, Instant?, Instant?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, String?, Int?, Instant?, Instant?, Instant?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, String?, Int?, Instant?, Instant?, Instant?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
