/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.GAMES_RESULTS_PKEY
import org.jooq.storage.keys.GAMES_RESULTS__GAMES_RESULTS_GAME_ID_FKEY
import org.jooq.storage.keys.GAMES_RESULTS__GAMES_RESULTS_LOSER_FKEY
import org.jooq.storage.keys.GAMES_RESULTS__GAMES_RESULTS_WINNER_FKEY
import org.jooq.storage.tables.Games.GamesPath
import org.jooq.storage.tables.Teams.TeamsPath
import org.jooq.storage.tables.records.GamesResultsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GamesResults(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GamesResultsRecord>?,
    parentPath: InverseForeignKey<out Record, GamesResultsRecord>?,
    aliased: Table<GamesResultsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GamesResultsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.games_results</code>
         */
        val GAMES_RESULTS: GamesResults = GamesResults()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GamesResultsRecord> = GamesResultsRecord::class.java

    /**
     * The column <code>dennys.games_results.game_id</code>.
     */
    val GAME_ID: TableField<GamesResultsRecord, Int?> = createField(DSL.name("game_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.games_results.winner</code>.
     */
    val WINNER: TableField<GamesResultsRecord, Int?> = createField(DSL.name("winner"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.games_results.loser</code>.
     */
    val LOSER: TableField<GamesResultsRecord, Int?> = createField(DSL.name("loser"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<GamesResultsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GamesResultsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GamesResultsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.games_results</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.games_results</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.games_results</code> table reference
     */
    constructor(): this(DSL.name("games_results"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GamesResultsRecord>?, parentPath: InverseForeignKey<out Record, GamesResultsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GAMES_RESULTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GamesResultsPath : GamesResults, Path<GamesResultsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GamesResultsRecord>?, parentPath: InverseForeignKey<out Record, GamesResultsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GamesResultsRecord>): super(alias, aliased)
        override fun `as`(alias: String): GamesResultsPath = GamesResultsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GamesResultsPath = GamesResultsPath(alias, this)
        override fun `as`(alias: Table<*>): GamesResultsPath = GamesResultsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<GamesResultsRecord> = GAMES_RESULTS_PKEY
    override fun getReferences(): List<ForeignKey<GamesResultsRecord, *>> = listOf(GAMES_RESULTS__GAMES_RESULTS_GAME_ID_FKEY, GAMES_RESULTS__GAMES_RESULTS_WINNER_FKEY, GAMES_RESULTS__GAMES_RESULTS_LOSER_FKEY)

    private lateinit var _games: GamesPath

    /**
     * Get the implicit join path to the <code>dennys.games</code> table.
     */
    fun games(): GamesPath {
        if (!this::_games.isInitialized)
            _games = GamesPath(this, GAMES_RESULTS__GAMES_RESULTS_GAME_ID_FKEY, null)

        return _games;
    }

    val games: GamesPath
        get(): GamesPath = games()

    private lateinit var _gamesResultsWinnerFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>games_results_winner_fkey</code> key.
     */
    fun gamesResultsWinnerFkey(): TeamsPath {
        if (!this::_gamesResultsWinnerFkey.isInitialized)
            _gamesResultsWinnerFkey = TeamsPath(this, GAMES_RESULTS__GAMES_RESULTS_WINNER_FKEY, null)

        return _gamesResultsWinnerFkey;
    }

    val gamesResultsWinnerFkey: TeamsPath
        get(): TeamsPath = gamesResultsWinnerFkey()

    private lateinit var _gamesResultsLoserFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>games_results_loser_fkey</code> key.
     */
    fun gamesResultsLoserFkey(): TeamsPath {
        if (!this::_gamesResultsLoserFkey.isInitialized)
            _gamesResultsLoserFkey = TeamsPath(this, GAMES_RESULTS__GAMES_RESULTS_LOSER_FKEY, null)

        return _gamesResultsLoserFkey;
    }

    val gamesResultsLoserFkey: TeamsPath
        get(): TeamsPath = gamesResultsLoserFkey()
    override fun `as`(alias: String): GamesResults = GamesResults(DSL.name(alias), this)
    override fun `as`(alias: Name): GamesResults = GamesResults(alias, this)
    override fun `as`(alias: Table<*>): GamesResults = GamesResults(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GamesResults = GamesResults(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GamesResults = GamesResults(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GamesResults = GamesResults(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GamesResults = GamesResults(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GamesResults = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GamesResults = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GamesResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GamesResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GamesResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GamesResults = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GamesResults = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GamesResults = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GamesResults = where(DSL.notExists(select))
}
