/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.GAME_RESULTS_PKEY
import org.jooq.storage.keys.GAME_RESULTS__GAME_RESULTS_GAME_ID_FKEY
import org.jooq.storage.keys.GAME_RESULTS__GAME_RESULTS_LOSER_TEAM_ID_FKEY
import org.jooq.storage.keys.GAME_RESULTS__GAME_RESULTS_WINNER_TEAM_ID_FKEY
import org.jooq.storage.tables.Games.GamesPath
import org.jooq.storage.tables.Teams.TeamsPath
import org.jooq.storage.tables.records.GameResultsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GameResults(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GameResultsRecord>?,
    parentPath: InverseForeignKey<out Record, GameResultsRecord>?,
    aliased: Table<GameResultsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GameResultsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.game_results</code>
         */
        val GAME_RESULTS: GameResults = GameResults()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GameResultsRecord> = GameResultsRecord::class.java

    /**
     * The column <code>dennys.game_results.game_id</code>.
     */
    val GAME_ID: TableField<GameResultsRecord, Int?> = createField(DSL.name("game_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.game_results.winner_team_id</code>.
     */
    val WINNER_TEAM_ID: TableField<GameResultsRecord, Int?> = createField(DSL.name("winner_team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.game_results.loser_team_id</code>.
     */
    val LOSER_TEAM_ID: TableField<GameResultsRecord, Int?> = createField(DSL.name("loser_team_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<GameResultsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GameResultsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GameResultsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.game_results</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.game_results</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.game_results</code> table reference
     */
    constructor(): this(DSL.name("game_results"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GameResultsRecord>?, parentPath: InverseForeignKey<out Record, GameResultsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GAME_RESULTS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GameResultsPath : GameResults, Path<GameResultsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GameResultsRecord>?, parentPath: InverseForeignKey<out Record, GameResultsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GameResultsRecord>): super(alias, aliased)
        override fun `as`(alias: String): GameResultsPath = GameResultsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GameResultsPath = GameResultsPath(alias, this)
        override fun `as`(alias: Table<*>): GameResultsPath = GameResultsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<GameResultsRecord> = GAME_RESULTS_PKEY
    override fun getReferences(): List<ForeignKey<GameResultsRecord, *>> = listOf(GAME_RESULTS__GAME_RESULTS_GAME_ID_FKEY, GAME_RESULTS__GAME_RESULTS_LOSER_TEAM_ID_FKEY, GAME_RESULTS__GAME_RESULTS_WINNER_TEAM_ID_FKEY)

    private lateinit var _games: GamesPath

    /**
     * Get the implicit join path to the <code>dennys.games</code> table.
     */
    fun games(): GamesPath {
        if (!this::_games.isInitialized)
            _games = GamesPath(this, GAME_RESULTS__GAME_RESULTS_GAME_ID_FKEY, null)

        return _games;
    }

    val games: GamesPath
        get(): GamesPath = games()

    private lateinit var _gameResultsLoserTeamIdFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>game_results_loser_team_id_fkey</code> key.
     */
    fun gameResultsLoserTeamIdFkey(): TeamsPath {
        if (!this::_gameResultsLoserTeamIdFkey.isInitialized)
            _gameResultsLoserTeamIdFkey = TeamsPath(this, GAME_RESULTS__GAME_RESULTS_LOSER_TEAM_ID_FKEY, null)

        return _gameResultsLoserTeamIdFkey;
    }

    val gameResultsLoserTeamIdFkey: TeamsPath
        get(): TeamsPath = gameResultsLoserTeamIdFkey()

    private lateinit var _gameResultsWinnerTeamIdFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>game_results_winner_team_id_fkey</code> key.
     */
    fun gameResultsWinnerTeamIdFkey(): TeamsPath {
        if (!this::_gameResultsWinnerTeamIdFkey.isInitialized)
            _gameResultsWinnerTeamIdFkey = TeamsPath(this, GAME_RESULTS__GAME_RESULTS_WINNER_TEAM_ID_FKEY, null)

        return _gameResultsWinnerTeamIdFkey;
    }

    val gameResultsWinnerTeamIdFkey: TeamsPath
        get(): TeamsPath = gameResultsWinnerTeamIdFkey()
    override fun `as`(alias: String): GameResults = GameResults(DSL.name(alias), this)
    override fun `as`(alias: Name): GameResults = GameResults(alias, this)
    override fun `as`(alias: Table<*>): GameResults = GameResults(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GameResults = GameResults(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GameResults = GameResults(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GameResults = GameResults(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GameResults = GameResults(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GameResults = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GameResults = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GameResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GameResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GameResults = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GameResults = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GameResults = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GameResults = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GameResults = where(DSL.notExists(select))
}
