/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.PERSONAL_ACCESS_TOKENS_PKEY
import org.jooq.storage.keys.PERSONAL_ACCESS_TOKENS__PERSONAL_ACCESS_TOKENS_USER_ID_FKEY
import org.jooq.storage.tables.Users.UsersPath
import org.jooq.storage.tables.records.PersonalAccessTokensRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PersonalAccessTokens(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PersonalAccessTokensRecord>?,
    parentPath: InverseForeignKey<out Record, PersonalAccessTokensRecord>?,
    aliased: Table<PersonalAccessTokensRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PersonalAccessTokensRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.personal_access_tokens</code>
         */
        val PERSONAL_ACCESS_TOKENS: PersonalAccessTokens = PersonalAccessTokens()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PersonalAccessTokensRecord> = PersonalAccessTokensRecord::class.java

    /**
     * The column <code>dennys.personal_access_tokens.token</code>.
     */
    val TOKEN: TableField<PersonalAccessTokensRecord, String?> = createField(DSL.name("token"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.personal_access_tokens.name</code>.
     */
    val NAME: TableField<PersonalAccessTokensRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.personal_access_tokens.user_id</code>.
     */
    val USER_ID: TableField<PersonalAccessTokensRecord, Int?> = createField(DSL.name("user_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.personal_access_tokens.scopes</code>.
     */
    val SCOPES: TableField<PersonalAccessTokensRecord, String?> = createField(DSL.name("scopes"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.personal_access_tokens.expires_at</code>.
     */
    val EXPIRES_AT: TableField<PersonalAccessTokensRecord, Instant?> = createField(DSL.name("expires_at"), SQLDataType.INSTANT.nullable(false), this, "")

    /**
     * The column <code>dennys.personal_access_tokens.created_at</code>.
     */
    val CREATED_AT: TableField<PersonalAccessTokensRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    private constructor(alias: Name, aliased: Table<PersonalAccessTokensRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PersonalAccessTokensRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PersonalAccessTokensRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.personal_access_tokens</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.personal_access_tokens</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.personal_access_tokens</code> table reference
     */
    constructor(): this(DSL.name("personal_access_tokens"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PersonalAccessTokensRecord>?, parentPath: InverseForeignKey<out Record, PersonalAccessTokensRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PERSONAL_ACCESS_TOKENS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PersonalAccessTokensPath : PersonalAccessTokens, Path<PersonalAccessTokensRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PersonalAccessTokensRecord>?, parentPath: InverseForeignKey<out Record, PersonalAccessTokensRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PersonalAccessTokensRecord>): super(alias, aliased)
        override fun `as`(alias: String): PersonalAccessTokensPath = PersonalAccessTokensPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PersonalAccessTokensPath = PersonalAccessTokensPath(alias, this)
        override fun `as`(alias: Table<*>): PersonalAccessTokensPath = PersonalAccessTokensPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<PersonalAccessTokensRecord> = PERSONAL_ACCESS_TOKENS_PKEY
    override fun getReferences(): List<ForeignKey<PersonalAccessTokensRecord, *>> = listOf(PERSONAL_ACCESS_TOKENS__PERSONAL_ACCESS_TOKENS_USER_ID_FKEY)

    private lateinit var _users: UsersPath

    /**
     * Get the implicit join path to the <code>dennys.users</code> table.
     */
    fun users(): UsersPath {
        if (!this::_users.isInitialized)
            _users = UsersPath(this, PERSONAL_ACCESS_TOKENS__PERSONAL_ACCESS_TOKENS_USER_ID_FKEY, null)

        return _users;
    }

    val users: UsersPath
        get(): UsersPath = users()
    override fun `as`(alias: String): PersonalAccessTokens = PersonalAccessTokens(DSL.name(alias), this)
    override fun `as`(alias: Name): PersonalAccessTokens = PersonalAccessTokens(alias, this)
    override fun `as`(alias: Table<*>): PersonalAccessTokens = PersonalAccessTokens(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PersonalAccessTokens = PersonalAccessTokens(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PersonalAccessTokens = PersonalAccessTokens(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PersonalAccessTokens = PersonalAccessTokens(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PersonalAccessTokens = PersonalAccessTokens(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PersonalAccessTokens = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PersonalAccessTokens = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PersonalAccessTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PersonalAccessTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PersonalAccessTokens = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PersonalAccessTokens = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PersonalAccessTokens = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PersonalAccessTokens = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PersonalAccessTokens = where(DSL.notExists(select))
}
