/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.PLAYER_FARMING_PKEY
import org.jooq.storage.keys.PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_FARMING_ID_FKEY
import org.jooq.storage.tables.PlayerGameFacts.PlayerGameFactsPath
import org.jooq.storage.tables.records.PlayerFarmingRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerFarming(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PlayerFarmingRecord>?,
    parentPath: InverseForeignKey<out Record, PlayerFarmingRecord>?,
    aliased: Table<PlayerFarmingRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PlayerFarmingRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_farming</code>
         */
        val PLAYER_FARMING: PlayerFarming = PlayerFarming()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerFarmingRecord> = PlayerFarmingRecord::class.java

    /**
     * The column <code>dennys.player_farming.id</code>.
     */
    val ID: TableField<PlayerFarmingRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.player_farming.total_gold</code>.
     */
    val TOTAL_GOLD: TableField<PlayerFarmingRecord, Int?> = createField(DSL.name("total_gold"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_farming.creep_score</code>.
     */
    val CREEP_SCORE: TableField<PlayerFarmingRecord, Int?> = createField(DSL.name("creep_score"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_farming.level</code>.
     */
    val LEVEL: TableField<PlayerFarmingRecord, Int?> = createField(DSL.name("level"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerFarmingRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PlayerFarmingRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PlayerFarmingRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.player_farming</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_farming</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_farming</code> table reference
     */
    constructor(): this(DSL.name("player_farming"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerFarmingRecord>?, parentPath: InverseForeignKey<out Record, PlayerFarmingRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PLAYER_FARMING, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PlayerFarmingPath : PlayerFarming, Path<PlayerFarmingRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PlayerFarmingRecord>?, parentPath: InverseForeignKey<out Record, PlayerFarmingRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PlayerFarmingRecord>): super(alias, aliased)
        override fun `as`(alias: String): PlayerFarmingPath = PlayerFarmingPath(DSL.name(alias), this)
        override fun `as`(alias: Name): PlayerFarmingPath = PlayerFarmingPath(alias, this)
        override fun `as`(alias: Table<*>): PlayerFarmingPath = PlayerFarmingPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<PlayerFarmingRecord, Int?> = super.getIdentity() as Identity<PlayerFarmingRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerFarmingRecord> = PLAYER_FARMING_PKEY

    private lateinit var _playerGameFacts: PlayerGameFactsPath

    /**
     * Get the implicit to-many join path to the
     * <code>dennys.player_game_facts</code> table
     */
    fun playerGameFacts(): PlayerGameFactsPath {
        if (!this::_playerGameFacts.isInitialized)
            _playerGameFacts = PlayerGameFactsPath(this, null, PLAYER_GAME_FACTS__PLAYER_GAME_FACTS_PLAYER_FARMING_ID_FKEY.inverseKey)

        return _playerGameFacts;
    }

    val playerGameFacts: PlayerGameFactsPath
        get(): PlayerGameFactsPath = playerGameFacts()
    override fun `as`(alias: String): PlayerFarming = PlayerFarming(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerFarming = PlayerFarming(alias, this)
    override fun `as`(alias: Table<*>): PlayerFarming = PlayerFarming(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerFarming = PlayerFarming(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerFarming = PlayerFarming(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerFarming = PlayerFarming(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PlayerFarming = PlayerFarming(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PlayerFarming = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PlayerFarming = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PlayerFarming = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PlayerFarming = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PlayerFarming = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PlayerFarming = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PlayerFarming = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PlayerFarming = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PlayerFarming = where(DSL.notExists(select))
}
