/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row8
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.PLAYER_INVENTORIES_PKEY
import org.jooq.storage.tables.records.PlayerInventoriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerInventories(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlayerInventoriesRecord>?,
    aliased: Table<PlayerInventoriesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlayerInventoriesRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_inventories</code>
         */
        val PLAYER_INVENTORIES: PlayerInventories = PlayerInventories()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerInventoriesRecord> = PlayerInventoriesRecord::class.java

    /**
     * The column <code>dennys.player_inventories.id</code>.
     */
    val ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.player_inventories.item0_id</code>.
     */
    val ITEM0_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item0_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item1_id</code>.
     */
    val ITEM1_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item1_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item2_id</code>.
     */
    val ITEM2_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item2_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item3_id</code>.
     */
    val ITEM3_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item3_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item4_id</code>.
     */
    val ITEM4_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item4_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.item5_id</code>.
     */
    val ITEM5_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("item5_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_inventories.trinket_id</code>.
     */
    val TRINKET_ID: TableField<PlayerInventoriesRecord, Int?> = createField(DSL.name("trinket_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlayerInventoriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.player_inventories</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_inventories</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_inventories</code> table reference
     */
    constructor(): this(DSL.name("player_inventories"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlayerInventoriesRecord>): this(Internal.createPathAlias(child, key), child, key, PLAYER_INVENTORIES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<PlayerInventoriesRecord, Int?> = super.getIdentity() as Identity<PlayerInventoriesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerInventoriesRecord> = PLAYER_INVENTORIES_PKEY
    override fun `as`(alias: String): PlayerInventories = PlayerInventories(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerInventories = PlayerInventories(alias, this)
    override fun `as`(alias: Table<*>): PlayerInventories = PlayerInventories(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerInventories = PlayerInventories(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerInventories = PlayerInventories(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerInventories = PlayerInventories(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row8<Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row8<Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
