/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.util.function.Function

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row10
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.PLAYER_PINGS_PKEY
import org.jooq.storage.tables.records.PlayerPingsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerPings(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, PlayerPingsRecord>?,
    aliased: Table<PlayerPingsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<PlayerPingsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.player_pings</code>
         */
        val PLAYER_PINGS: PlayerPings = PlayerPings()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PlayerPingsRecord> = PlayerPingsRecord::class.java

    /**
     * The column <code>dennys.player_pings.id</code>.
     */
    val ID: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.player_pings.on_my_way_count</code>.
     */
    val ON_MY_WAY_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("on_my_way_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.enemy_missing_count</code>.
     */
    val ENEMY_MISSING_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("enemy_missing_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.assist_me_count</code>.
     */
    val ASSIST_ME_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("assist_me_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.get_back_count</code>.
     */
    val GET_BACK_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("get_back_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.enemy_vision_count</code>.
     */
    val ENEMY_VISION_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("enemy_vision_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.all_in_count</code>.
     */
    val ALL_IN_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("all_in_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.need_vision_count</code>.
     */
    val NEED_VISION_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("need_vision_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.push_count</code>.
     */
    val PUSH_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("push_count"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.player_pings.vision_cleared_count</code>.
     */
    val VISION_CLEARED_COUNT: TableField<PlayerPingsRecord, Int?> = createField(DSL.name("vision_cleared_count"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PlayerPingsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<PlayerPingsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.player_pings</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.player_pings</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.player_pings</code> table reference
     */
    constructor(): this(DSL.name("player_pings"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, PlayerPingsRecord>): this(Internal.createPathAlias(child, key), child, key, PLAYER_PINGS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<PlayerPingsRecord, Int?> = super.getIdentity() as Identity<PlayerPingsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<PlayerPingsRecord> = PLAYER_PINGS_PKEY
    override fun `as`(alias: String): PlayerPings = PlayerPings(DSL.name(alias), this)
    override fun `as`(alias: Name): PlayerPings = PlayerPings(alias, this)
    override fun `as`(alias: Table<*>): PlayerPings = PlayerPings(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PlayerPings = PlayerPings(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PlayerPings = PlayerPings(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PlayerPings = PlayerPings(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row10<Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row10<Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
