/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.RIOT_ACCOUNTS_AUDIT_LOGS_PKEY
import org.jooq.storage.keys.RIOT_ACCOUNTS_AUDIT_LOGS__RIOT_ACCOUNTS_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY
import org.jooq.storage.tables.records.RiotAccountsAuditLogsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RiotAccountsAuditLogs(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, RiotAccountsAuditLogsRecord>?,
    aliased: Table<RiotAccountsAuditLogsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<RiotAccountsAuditLogsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of
         * <code>dennys.riot_accounts_audit_logs</code>
         */
        val RIOT_ACCOUNTS_AUDIT_LOGS: RiotAccountsAuditLogs = RiotAccountsAuditLogs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RiotAccountsAuditLogsRecord> = RiotAccountsAuditLogsRecord::class.java

    /**
     * The column <code>dennys.riot_accounts_audit_logs.id</code>.
     */
    val ID: TableField<RiotAccountsAuditLogsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.riot_accounts_audit_logs.created_at</code>.
     */
    val CREATED_AT: TableField<RiotAccountsAuditLogsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>dennys.riot_accounts_audit_logs.riot_account_id</code>.
     */
    val RIOT_ACCOUNT_ID: TableField<RiotAccountsAuditLogsRecord, Int?> = createField(DSL.name("riot_account_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.riot_accounts_audit_logs.action</code>.
     */
    val ACTION: TableField<RiotAccountsAuditLogsRecord, String?> = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.riot_accounts_audit_logs.message</code>.
     */
    val MESSAGE: TableField<RiotAccountsAuditLogsRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.riot_accounts_audit_logs.origin</code>.
     */
    val ORIGIN: TableField<RiotAccountsAuditLogsRecord, String?> = createField(DSL.name("origin"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RiotAccountsAuditLogsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<RiotAccountsAuditLogsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.riot_accounts_audit_logs</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.riot_accounts_audit_logs</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.riot_accounts_audit_logs</code> table reference
     */
    constructor(): this(DSL.name("riot_accounts_audit_logs"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, RiotAccountsAuditLogsRecord>): this(Internal.createPathAlias(child, key), child, key, RIOT_ACCOUNTS_AUDIT_LOGS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<RiotAccountsAuditLogsRecord, Int?> = super.getIdentity() as Identity<RiotAccountsAuditLogsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<RiotAccountsAuditLogsRecord> = RIOT_ACCOUNTS_AUDIT_LOGS_PKEY
    override fun getReferences(): List<ForeignKey<RiotAccountsAuditLogsRecord, *>> = listOf(RIOT_ACCOUNTS_AUDIT_LOGS__RIOT_ACCOUNTS_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY)

    private lateinit var _riotAccounts: RiotAccounts

    /**
     * Get the implicit join path to the <code>dennys.riot_accounts</code>
     * table.
     */
    fun riotAccounts(): RiotAccounts {
        if (!this::_riotAccounts.isInitialized)
            _riotAccounts = RiotAccounts(this, RIOT_ACCOUNTS_AUDIT_LOGS__RIOT_ACCOUNTS_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY)

        return _riotAccounts;
    }

    val riotAccounts: RiotAccounts
        get(): RiotAccounts = riotAccounts()
    override fun `as`(alias: String): RiotAccountsAuditLogs = RiotAccountsAuditLogs(DSL.name(alias), this)
    override fun `as`(alias: Name): RiotAccountsAuditLogs = RiotAccountsAuditLogs(alias, this)
    override fun `as`(alias: Table<*>): RiotAccountsAuditLogs = RiotAccountsAuditLogs(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RiotAccountsAuditLogs = RiotAccountsAuditLogs(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RiotAccountsAuditLogs = RiotAccountsAuditLogs(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RiotAccountsAuditLogs = RiotAccountsAuditLogs(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, Instant?, Int?, String?, String?, String?> = super.fieldsRow() as Row6<Int?, Instant?, Int?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Instant?, Int?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Instant?, Int?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
