/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.RIOT_ACCOUNT_AUDIT_LOGS_PKEY
import org.jooq.storage.keys.RIOT_ACCOUNT_AUDIT_LOGS__RIOT_ACCOUNT_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY
import org.jooq.storage.tables.RiotAccounts.RiotAccountsPath
import org.jooq.storage.tables.records.RiotAccountAuditLogsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RiotAccountAuditLogs(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RiotAccountAuditLogsRecord>?,
    parentPath: InverseForeignKey<out Record, RiotAccountAuditLogsRecord>?,
    aliased: Table<RiotAccountAuditLogsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RiotAccountAuditLogsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.riot_account_audit_logs</code>
         */
        val RIOT_ACCOUNT_AUDIT_LOGS: RiotAccountAuditLogs = RiotAccountAuditLogs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RiotAccountAuditLogsRecord> = RiotAccountAuditLogsRecord::class.java

    /**
     * The column <code>dennys.riot_account_audit_logs.id</code>.
     */
    val ID: TableField<RiotAccountAuditLogsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.riot_account_audit_logs.created_at</code>.
     */
    val CREATED_AT: TableField<RiotAccountAuditLogsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>dennys.riot_account_audit_logs.riot_account_id</code>.
     */
    val RIOT_ACCOUNT_ID: TableField<RiotAccountAuditLogsRecord, Int?> = createField(DSL.name("riot_account_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.riot_account_audit_logs.action</code>.
     */
    val ACTION: TableField<RiotAccountAuditLogsRecord, String?> = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.riot_account_audit_logs.message</code>.
     */
    val MESSAGE: TableField<RiotAccountAuditLogsRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.riot_account_audit_logs.origin</code>.
     */
    val ORIGIN: TableField<RiotAccountAuditLogsRecord, String?> = createField(DSL.name("origin"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RiotAccountAuditLogsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RiotAccountAuditLogsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RiotAccountAuditLogsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.riot_account_audit_logs</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.riot_account_audit_logs</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.riot_account_audit_logs</code> table reference
     */
    constructor(): this(DSL.name("riot_account_audit_logs"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RiotAccountAuditLogsRecord>?, parentPath: InverseForeignKey<out Record, RiotAccountAuditLogsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, RIOT_ACCOUNT_AUDIT_LOGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RiotAccountAuditLogsPath : RiotAccountAuditLogs, Path<RiotAccountAuditLogsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RiotAccountAuditLogsRecord>?, parentPath: InverseForeignKey<out Record, RiotAccountAuditLogsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RiotAccountAuditLogsRecord>): super(alias, aliased)
        override fun `as`(alias: String): RiotAccountAuditLogsPath = RiotAccountAuditLogsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RiotAccountAuditLogsPath = RiotAccountAuditLogsPath(alias, this)
        override fun `as`(alias: Table<*>): RiotAccountAuditLogsPath = RiotAccountAuditLogsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<RiotAccountAuditLogsRecord, Int?> = super.getIdentity() as Identity<RiotAccountAuditLogsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<RiotAccountAuditLogsRecord> = RIOT_ACCOUNT_AUDIT_LOGS_PKEY
    override fun getReferences(): List<ForeignKey<RiotAccountAuditLogsRecord, *>> = listOf(RIOT_ACCOUNT_AUDIT_LOGS__RIOT_ACCOUNT_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY)

    private lateinit var _riotAccounts: RiotAccountsPath

    /**
     * Get the implicit join path to the <code>dennys.riot_accounts</code>
     * table.
     */
    fun riotAccounts(): RiotAccountsPath {
        if (!this::_riotAccounts.isInitialized)
            _riotAccounts = RiotAccountsPath(this, RIOT_ACCOUNT_AUDIT_LOGS__RIOT_ACCOUNT_AUDIT_LOGS_RIOT_ACCOUNT_ID_FKEY, null)

        return _riotAccounts;
    }

    val riotAccounts: RiotAccountsPath
        get(): RiotAccountsPath = riotAccounts()
    override fun `as`(alias: String): RiotAccountAuditLogs = RiotAccountAuditLogs(DSL.name(alias), this)
    override fun `as`(alias: Name): RiotAccountAuditLogs = RiotAccountAuditLogs(alias, this)
    override fun `as`(alias: Table<*>): RiotAccountAuditLogs = RiotAccountAuditLogs(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RiotAccountAuditLogs = RiotAccountAuditLogs(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RiotAccountAuditLogs = RiotAccountAuditLogs(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RiotAccountAuditLogs = RiotAccountAuditLogs(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RiotAccountAuditLogs = RiotAccountAuditLogs(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RiotAccountAuditLogs = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RiotAccountAuditLogs = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RiotAccountAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RiotAccountAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RiotAccountAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RiotAccountAuditLogs = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RiotAccountAuditLogs = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RiotAccountAuditLogs = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RiotAccountAuditLogs = where(DSL.notExists(select))
}
