/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.RIOT_ACCOUNT_TO_PLAYER_PKEY
import org.jooq.storage.keys.RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_PLAYER_ID_FKEY
import org.jooq.storage.keys.RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_RIOT_ACCOUNT_ID_FKEY
import org.jooq.storage.tables.Players.PlayersPath
import org.jooq.storage.tables.RiotAccounts.RiotAccountsPath
import org.jooq.storage.tables.records.RiotAccountToPlayerRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RiotAccountToPlayer(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, RiotAccountToPlayerRecord>?,
    parentPath: InverseForeignKey<out Record, RiotAccountToPlayerRecord>?,
    aliased: Table<RiotAccountToPlayerRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<RiotAccountToPlayerRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.riot_account_to_player</code>
         */
        val RIOT_ACCOUNT_TO_PLAYER: RiotAccountToPlayer = RiotAccountToPlayer()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<RiotAccountToPlayerRecord> = RiotAccountToPlayerRecord::class.java

    /**
     * The column <code>dennys.riot_account_to_player.player_id</code>.
     */
    val PLAYER_ID: TableField<RiotAccountToPlayerRecord, Int?> = createField(DSL.name("player_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.riot_account_to_player.riot_account_id</code>.
     */
    val RIOT_ACCOUNT_ID: TableField<RiotAccountToPlayerRecord, Int?> = createField(DSL.name("riot_account_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<RiotAccountToPlayerRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<RiotAccountToPlayerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<RiotAccountToPlayerRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.riot_account_to_player</code> table
     * reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.riot_account_to_player</code> table
     * reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.riot_account_to_player</code> table reference
     */
    constructor(): this(DSL.name("riot_account_to_player"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RiotAccountToPlayerRecord>?, parentPath: InverseForeignKey<out Record, RiotAccountToPlayerRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, RIOT_ACCOUNT_TO_PLAYER, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RiotAccountToPlayerPath : RiotAccountToPlayer, Path<RiotAccountToPlayerRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, RiotAccountToPlayerRecord>?, parentPath: InverseForeignKey<out Record, RiotAccountToPlayerRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<RiotAccountToPlayerRecord>): super(alias, aliased)
        override fun `as`(alias: String): RiotAccountToPlayerPath = RiotAccountToPlayerPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RiotAccountToPlayerPath = RiotAccountToPlayerPath(alias, this)
        override fun `as`(alias: Table<*>): RiotAccountToPlayerPath = RiotAccountToPlayerPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<RiotAccountToPlayerRecord> = RIOT_ACCOUNT_TO_PLAYER_PKEY
    override fun getReferences(): List<ForeignKey<RiotAccountToPlayerRecord, *>> = listOf(RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_PLAYER_ID_FKEY, RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_RIOT_ACCOUNT_ID_FKEY)

    private lateinit var _players: PlayersPath

    /**
     * Get the implicit join path to the <code>dennys.players</code> table.
     */
    fun players(): PlayersPath {
        if (!this::_players.isInitialized)
            _players = PlayersPath(this, RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_PLAYER_ID_FKEY, null)

        return _players;
    }

    val players: PlayersPath
        get(): PlayersPath = players()

    private lateinit var _riotAccounts: RiotAccountsPath

    /**
     * Get the implicit join path to the <code>dennys.riot_accounts</code>
     * table.
     */
    fun riotAccounts(): RiotAccountsPath {
        if (!this::_riotAccounts.isInitialized)
            _riotAccounts = RiotAccountsPath(this, RIOT_ACCOUNT_TO_PLAYER__RIOT_ACCOUNT_TO_PLAYER_RIOT_ACCOUNT_ID_FKEY, null)

        return _riotAccounts;
    }

    val riotAccounts: RiotAccountsPath
        get(): RiotAccountsPath = riotAccounts()
    override fun `as`(alias: String): RiotAccountToPlayer = RiotAccountToPlayer(DSL.name(alias), this)
    override fun `as`(alias: Name): RiotAccountToPlayer = RiotAccountToPlayer(alias, this)
    override fun `as`(alias: Table<*>): RiotAccountToPlayer = RiotAccountToPlayer(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): RiotAccountToPlayer = RiotAccountToPlayer(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RiotAccountToPlayer = RiotAccountToPlayer(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RiotAccountToPlayer = RiotAccountToPlayer(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): RiotAccountToPlayer = RiotAccountToPlayer(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): RiotAccountToPlayer = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): RiotAccountToPlayer = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): RiotAccountToPlayer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): RiotAccountToPlayer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): RiotAccountToPlayer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): RiotAccountToPlayer = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): RiotAccountToPlayer = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): RiotAccountToPlayer = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): RiotAccountToPlayer = where(DSL.notExists(select))
}
