/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row2
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.SERIES_PARTICIPANTS_PKEY
import org.jooq.storage.keys.SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY
import org.jooq.storage.keys.SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY
import org.jooq.storage.tables.records.SeriesParticipantsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesParticipants(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SeriesParticipantsRecord>?,
    aliased: Table<SeriesParticipantsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SeriesParticipantsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.series_participants</code>
         */
        val SERIES_PARTICIPANTS: SeriesParticipants = SeriesParticipants()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SeriesParticipantsRecord> = SeriesParticipantsRecord::class.java

    /**
     * The column <code>dennys.series_participants.team_id</code>.
     */
    val TEAM_ID: TableField<SeriesParticipantsRecord, Int?> = createField(DSL.name("team_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>dennys.series_participants.series_id</code>.
     */
    val SERIES_ID: TableField<SeriesParticipantsRecord, Int?> = createField(DSL.name("series_id"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SeriesParticipantsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.series_participants</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.series_participants</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.series_participants</code> table reference
     */
    constructor(): this(DSL.name("series_participants"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SeriesParticipantsRecord>): this(Internal.createPathAlias(child, key), child, key, SERIES_PARTICIPANTS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getPrimaryKey(): UniqueKey<SeriesParticipantsRecord> = SERIES_PARTICIPANTS_PKEY
    override fun getReferences(): List<ForeignKey<SeriesParticipantsRecord, *>> = listOf(SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY)

    private lateinit var _teams: Teams
    private lateinit var _series: Series

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table.
     */
    fun teams(): Teams {
        if (!this::_teams.isInitialized)
            _teams = Teams(this, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_TEAM_ID_FKEY)

        return _teams;
    }

    val teams: Teams
        get(): Teams = teams()

    /**
     * Get the implicit join path to the <code>dennys.series</code> table.
     */
    fun series(): Series {
        if (!this::_series.isInitialized)
            _series = Series(this, SERIES_PARTICIPANTS__SERIES_PARTICIPANTS_SERIES_ID_FKEY)

        return _series;
    }

    val series: Series
        get(): Series = series()
    override fun `as`(alias: String): SeriesParticipants = SeriesParticipants(DSL.name(alias), this)
    override fun `as`(alias: Name): SeriesParticipants = SeriesParticipants(alias, this)
    override fun `as`(alias: Table<*>): SeriesParticipants = SeriesParticipants(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): SeriesParticipants = SeriesParticipants(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): SeriesParticipants = SeriesParticipants(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): SeriesParticipants = SeriesParticipants(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row2<Int?, Int?> = super.fieldsRow() as Row2<Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
