/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row3
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.SERIES_PKEY
import org.jooq.storage.keys.SERIES__SERIES_EVENT_ID_FKEY
import org.jooq.storage.tables.records.SeriesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Series(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, SeriesRecord>?,
    aliased: Table<SeriesRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<SeriesRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.series</code>
         */
        val SERIES: Series = Series()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<SeriesRecord> = SeriesRecord::class.java

    /**
     * The column <code>dennys.series.id</code>.
     */
    val ID: TableField<SeriesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.series.event_id</code>.
     */
    val EVENT_ID: TableField<SeriesRecord, Int?> = createField(DSL.name("event_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.series.games_to_win</code>.
     */
    val GAMES_TO_WIN: TableField<SeriesRecord, Int?> = createField(DSL.name("games_to_win"), SQLDataType.INTEGER.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<SeriesRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<SeriesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.series</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.series</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.series</code> table reference
     */
    constructor(): this(DSL.name("series"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, SeriesRecord>): this(Internal.createPathAlias(child, key), child, key, SERIES, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<SeriesRecord, Int?> = super.getIdentity() as Identity<SeriesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<SeriesRecord> = SERIES_PKEY
    override fun getReferences(): List<ForeignKey<SeriesRecord, *>> = listOf(SERIES__SERIES_EVENT_ID_FKEY)

    private lateinit var _events: Events

    /**
     * Get the implicit join path to the <code>dennys.events</code> table.
     */
    fun events(): Events {
        if (!this::_events.isInitialized)
            _events = Events(this, SERIES__SERIES_EVENT_ID_FKEY)

        return _events;
    }

    val events: Events
        get(): Events = events()
    override fun `as`(alias: String): Series = Series(DSL.name(alias), this)
    override fun `as`(alias: Name): Series = Series(alias, this)
    override fun `as`(alias: Table<*>): Series = Series(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Series = Series(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Series = Series(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Series = Series(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row3<Int?, Int?, Int?> = super.fieldsRow() as Row3<Int?, Int?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Int?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
