/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row4
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.TEAMS_PKEY
import org.jooq.storage.keys.TEAMS__TEAMS_EVENT_ID_FKEY
import org.jooq.storage.tables.records.TeamsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Teams(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TeamsRecord>?,
    aliased: Table<TeamsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TeamsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.teams</code>
         */
        val TEAMS: Teams = Teams()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamsRecord> = TeamsRecord::class.java

    /**
     * The column <code>dennys.teams.id</code>.
     */
    val ID: TableField<TeamsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.teams.name</code>.
     */
    val NAME: TableField<TeamsRecord, String?> = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.teams.logo_name</code>.
     */
    val LOGO_NAME: TableField<TeamsRecord, String?> = createField(DSL.name("logo_name"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>dennys.teams.event_id</code>.
     */
    val EVENT_ID: TableField<TeamsRecord, Int?> = createField(DSL.name("event_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<TeamsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TeamsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.teams</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.teams</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.teams</code> table reference
     */
    constructor(): this(DSL.name("teams"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TeamsRecord>): this(Internal.createPathAlias(child, key), child, key, TEAMS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<TeamsRecord, Int?> = super.getIdentity() as Identity<TeamsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TeamsRecord> = TEAMS_PKEY
    override fun getReferences(): List<ForeignKey<TeamsRecord, *>> = listOf(TEAMS__TEAMS_EVENT_ID_FKEY)

    private lateinit var _events: Events

    /**
     * Get the implicit join path to the <code>dennys.events</code> table.
     */
    fun events(): Events {
        if (!this::_events.isInitialized)
            _events = Events(this, TEAMS__TEAMS_EVENT_ID_FKEY)

        return _events;
    }

    val events: Events
        get(): Events = events()
    override fun `as`(alias: String): Teams = Teams(DSL.name(alias), this)
    override fun `as`(alias: Name): Teams = Teams(alias, this)
    override fun `as`(alias: Table<*>): Teams = Teams(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Teams = Teams(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Teams = Teams(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Teams = Teams(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row4<Int?, String?, String?, Int?> = super.fieldsRow() as Row4<Int?, String?, String?, Int?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, String?, String?, Int?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
