/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.TEAM_AUDIT_LOGS_PKEY
import org.jooq.storage.keys.TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY
import org.jooq.storage.tables.Teams.TeamsPath
import org.jooq.storage.tables.records.TeamAuditLogsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamAuditLogs(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TeamAuditLogsRecord>?,
    parentPath: InverseForeignKey<out Record, TeamAuditLogsRecord>?,
    aliased: Table<TeamAuditLogsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TeamAuditLogsRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.team_audit_logs</code>
         */
        val TEAM_AUDIT_LOGS: TeamAuditLogs = TeamAuditLogs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamAuditLogsRecord> = TeamAuditLogsRecord::class.java

    /**
     * The column <code>dennys.team_audit_logs.id</code>.
     */
    val ID: TableField<TeamAuditLogsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.team_audit_logs.created_at</code>.
     */
    val CREATED_AT: TableField<TeamAuditLogsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>dennys.team_audit_logs.team_id</code>.
     */
    val TEAM_ID: TableField<TeamAuditLogsRecord, Int?> = createField(DSL.name("team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.team_audit_logs.action</code>.
     */
    val ACTION: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.team_audit_logs.message</code>.
     */
    val MESSAGE: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.team_audit_logs.origin</code>.
     */
    val ORIGIN: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("origin"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.team_audit_logs</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.team_audit_logs</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.team_audit_logs</code> table reference
     */
    constructor(): this(DSL.name("team_audit_logs"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamAuditLogsRecord>?, parentPath: InverseForeignKey<out Record, TeamAuditLogsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TEAM_AUDIT_LOGS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TeamAuditLogsPath : TeamAuditLogs, Path<TeamAuditLogsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TeamAuditLogsRecord>?, parentPath: InverseForeignKey<out Record, TeamAuditLogsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>): super(alias, aliased)
        override fun `as`(alias: String): TeamAuditLogsPath = TeamAuditLogsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TeamAuditLogsPath = TeamAuditLogsPath(alias, this)
        override fun `as`(alias: Table<*>): TeamAuditLogsPath = TeamAuditLogsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<TeamAuditLogsRecord, Int?> = super.getIdentity() as Identity<TeamAuditLogsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TeamAuditLogsRecord> = TEAM_AUDIT_LOGS_PKEY
    override fun getReferences(): List<ForeignKey<TeamAuditLogsRecord, *>> = listOf(TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY)

    private lateinit var _teams: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table.
     */
    fun teams(): TeamsPath {
        if (!this::_teams.isInitialized)
            _teams = TeamsPath(this, TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY, null)

        return _teams;
    }

    val teams: TeamsPath
        get(): TeamsPath = teams()
    override fun `as`(alias: String): TeamAuditLogs = TeamAuditLogs(DSL.name(alias), this)
    override fun `as`(alias: Name): TeamAuditLogs = TeamAuditLogs(alias, this)
    override fun `as`(alias: Table<*>): TeamAuditLogs = TeamAuditLogs(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TeamAuditLogs = TeamAuditLogs(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TeamAuditLogs = TeamAuditLogs(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TeamAuditLogs = TeamAuditLogs(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TeamAuditLogs = TeamAuditLogs(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TeamAuditLogs = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TeamAuditLogs = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TeamAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TeamAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TeamAuditLogs = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TeamAuditLogs = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TeamAuditLogs = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TeamAuditLogs = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TeamAuditLogs = where(DSL.notExists(select))
}
