/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant
import java.util.function.Function

import kotlin.collections.List

import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Name
import org.jooq.Record
import org.jooq.Records
import org.jooq.Row6
import org.jooq.Schema
import org.jooq.SelectField
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.TEAM_AUDIT_LOGS_PKEY
import org.jooq.storage.keys.TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY
import org.jooq.storage.tables.records.TeamAuditLogsRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamAuditLogs(
    alias: Name,
    child: Table<out Record>?,
    path: ForeignKey<out Record, TeamAuditLogsRecord>?,
    aliased: Table<TeamAuditLogsRecord>?,
    parameters: Array<Field<*>?>?
): TableImpl<TeamAuditLogsRecord>(
    alias,
    Dennys.DENNYS,
    child,
    path,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table()
) {
    companion object {

        /**
         * The reference instance of <code>dennys.team_audit_logs</code>
         */
        val TEAM_AUDIT_LOGS: TeamAuditLogs = TeamAuditLogs()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TeamAuditLogsRecord> = TeamAuditLogsRecord::class.java

    /**
     * The column <code>dennys.team_audit_logs.id</code>.
     */
    val ID: TableField<TeamAuditLogsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.team_audit_logs.created_at</code>.
     */
    val CREATED_AT: TableField<TeamAuditLogsRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    /**
     * The column <code>dennys.team_audit_logs.team_id</code>.
     */
    val TEAM_ID: TableField<TeamAuditLogsRecord, Int?> = createField(DSL.name("team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.team_audit_logs.action</code>.
     */
    val ACTION: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("action"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.team_audit_logs.message</code>.
     */
    val MESSAGE: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("message"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.team_audit_logs.origin</code>.
     */
    val ORIGIN: TableField<TeamAuditLogsRecord, String?> = createField(DSL.name("origin"), SQLDataType.CLOB.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>?): this(alias, null, null, aliased, null)
    private constructor(alias: Name, aliased: Table<TeamAuditLogsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, aliased, parameters)

    /**
     * Create an aliased <code>dennys.team_audit_logs</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.team_audit_logs</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.team_audit_logs</code> table reference
     */
    constructor(): this(DSL.name("team_audit_logs"), null)

    constructor(child: Table<out Record>, key: ForeignKey<out Record, TeamAuditLogsRecord>): this(Internal.createPathAlias(child, key), child, key, TEAM_AUDIT_LOGS, null)
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<TeamAuditLogsRecord, Int?> = super.getIdentity() as Identity<TeamAuditLogsRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TeamAuditLogsRecord> = TEAM_AUDIT_LOGS_PKEY
    override fun getReferences(): List<ForeignKey<TeamAuditLogsRecord, *>> = listOf(TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY)

    private lateinit var _teams: Teams

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table.
     */
    fun teams(): Teams {
        if (!this::_teams.isInitialized)
            _teams = Teams(this, TEAM_AUDIT_LOGS__TEAM_AUDIT_LOGS_TEAM_ID_FKEY)

        return _teams;
    }

    val teams: Teams
        get(): Teams = teams()
    override fun `as`(alias: String): TeamAuditLogs = TeamAuditLogs(DSL.name(alias), this)
    override fun `as`(alias: Name): TeamAuditLogs = TeamAuditLogs(alias, this)
    override fun `as`(alias: Table<*>): TeamAuditLogs = TeamAuditLogs(alias.getQualifiedName(), this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TeamAuditLogs = TeamAuditLogs(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TeamAuditLogs = TeamAuditLogs(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TeamAuditLogs = TeamAuditLogs(name.getQualifiedName(), null)

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------
    override fun fieldsRow(): Row6<Int?, Instant?, Int?, String?, String?, String?> = super.fieldsRow() as Row6<Int?, Instant?, Int?, String?, String?, String?>

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    fun <U> mapping(from: (Int?, Instant?, Int?, String?, String?, String?) -> U): SelectField<U> = convertFrom(Records.mapping(from))

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    fun <U> mapping(toType: Class<U>, from: (Int?, Instant?, Int?, String?, String?, String?) -> U): SelectField<U> = convertFrom(toType, Records.mapping(from))
}
