/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables


import java.time.Instant

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import org.jooq.storage.Dennys
import org.jooq.storage.keys.GAMES__GAMES_TOURNAMENT_CODE_ID_FKEY
import org.jooq.storage.keys.TOURNAMENT_CODES_PKEY
import org.jooq.storage.keys.TOURNAMENT_CODES_SHORTCODE_KEY
import org.jooq.storage.keys.TOURNAMENT_CODES__TOURNAMENT_CODES_BLUE_TEAM_ID_FKEY
import org.jooq.storage.keys.TOURNAMENT_CODES__TOURNAMENT_CODES_RED_TEAM_ID_FKEY
import org.jooq.storage.keys.TOURNAMENT_CODES__TOURNAMENT_CODES_SERIES_ID_FKEY
import org.jooq.storage.tables.Games.GamesPath
import org.jooq.storage.tables.Series.SeriesPath
import org.jooq.storage.tables.Teams.TeamsPath
import org.jooq.storage.tables.records.TournamentCodesRecord


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentCodes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TournamentCodesRecord>?,
    parentPath: InverseForeignKey<out Record, TournamentCodesRecord>?,
    aliased: Table<TournamentCodesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TournamentCodesRecord>(
    alias,
    Dennys.DENNYS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>dennys.tournament_codes</code>
         */
        val TOURNAMENT_CODES: TournamentCodes = TournamentCodes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TournamentCodesRecord> = TournamentCodesRecord::class.java

    /**
     * The column <code>dennys.tournament_codes.id</code>.
     */
    val ID: TableField<TournamentCodesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>dennys.tournament_codes.shortcode</code>.
     */
    val SHORTCODE: TableField<TournamentCodesRecord, String?> = createField(DSL.name("shortcode"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>dennys.tournament_codes.blue_team_id</code>.
     */
    val BLUE_TEAM_ID: TableField<TournamentCodesRecord, Int?> = createField(DSL.name("blue_team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.tournament_codes.red_team_id</code>.
     */
    val RED_TEAM_ID: TableField<TournamentCodesRecord, Int?> = createField(DSL.name("red_team_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.tournament_codes.series_id</code>.
     */
    val SERIES_ID: TableField<TournamentCodesRecord, Int?> = createField(DSL.name("series_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>dennys.tournament_codes.created_at</code>.
     */
    val CREATED_AT: TableField<TournamentCodesRecord, Instant?> = createField(DSL.name("created_at"), SQLDataType.INSTANT.nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.INSTANT)), this, "")

    private constructor(alias: Name, aliased: Table<TournamentCodesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TournamentCodesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TournamentCodesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>dennys.tournament_codes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>dennys.tournament_codes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>dennys.tournament_codes</code> table reference
     */
    constructor(): this(DSL.name("tournament_codes"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentCodesRecord>?, parentPath: InverseForeignKey<out Record, TournamentCodesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, TOURNAMENT_CODES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class TournamentCodesPath : TournamentCodes, Path<TournamentCodesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, TournamentCodesRecord>?, parentPath: InverseForeignKey<out Record, TournamentCodesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<TournamentCodesRecord>): super(alias, aliased)
        override fun `as`(alias: String): TournamentCodesPath = TournamentCodesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): TournamentCodesPath = TournamentCodesPath(alias, this)
        override fun `as`(alias: Table<*>): TournamentCodesPath = TournamentCodesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Dennys.DENNYS
    override fun getIdentity(): Identity<TournamentCodesRecord, Int?> = super.getIdentity() as Identity<TournamentCodesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<TournamentCodesRecord> = TOURNAMENT_CODES_PKEY
    override fun getUniqueKeys(): List<UniqueKey<TournamentCodesRecord>> = listOf(TOURNAMENT_CODES_SHORTCODE_KEY)
    override fun getReferences(): List<ForeignKey<TournamentCodesRecord, *>> = listOf(TOURNAMENT_CODES__TOURNAMENT_CODES_BLUE_TEAM_ID_FKEY, TOURNAMENT_CODES__TOURNAMENT_CODES_RED_TEAM_ID_FKEY, TOURNAMENT_CODES__TOURNAMENT_CODES_SERIES_ID_FKEY)

    private lateinit var _tournamentCodesBlueTeamIdFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>tournament_codes_blue_team_id_fkey</code> key.
     */
    fun tournamentCodesBlueTeamIdFkey(): TeamsPath {
        if (!this::_tournamentCodesBlueTeamIdFkey.isInitialized)
            _tournamentCodesBlueTeamIdFkey = TeamsPath(this, TOURNAMENT_CODES__TOURNAMENT_CODES_BLUE_TEAM_ID_FKEY, null)

        return _tournamentCodesBlueTeamIdFkey;
    }

    val tournamentCodesBlueTeamIdFkey: TeamsPath
        get(): TeamsPath = tournamentCodesBlueTeamIdFkey()

    private lateinit var _tournamentCodesRedTeamIdFkey: TeamsPath

    /**
     * Get the implicit join path to the <code>dennys.teams</code> table, via
     * the <code>tournament_codes_red_team_id_fkey</code> key.
     */
    fun tournamentCodesRedTeamIdFkey(): TeamsPath {
        if (!this::_tournamentCodesRedTeamIdFkey.isInitialized)
            _tournamentCodesRedTeamIdFkey = TeamsPath(this, TOURNAMENT_CODES__TOURNAMENT_CODES_RED_TEAM_ID_FKEY, null)

        return _tournamentCodesRedTeamIdFkey;
    }

    val tournamentCodesRedTeamIdFkey: TeamsPath
        get(): TeamsPath = tournamentCodesRedTeamIdFkey()

    private lateinit var _series: SeriesPath

    /**
     * Get the implicit join path to the <code>dennys.series</code> table.
     */
    fun series(): SeriesPath {
        if (!this::_series.isInitialized)
            _series = SeriesPath(this, TOURNAMENT_CODES__TOURNAMENT_CODES_SERIES_ID_FKEY, null)

        return _series;
    }

    val series: SeriesPath
        get(): SeriesPath = series()

    private lateinit var _games: GamesPath

    /**
     * Get the implicit to-many join path to the <code>dennys.games</code> table
     */
    fun games(): GamesPath {
        if (!this::_games.isInitialized)
            _games = GamesPath(this, null, GAMES__GAMES_TOURNAMENT_CODE_ID_FKEY.inverseKey)

        return _games;
    }

    val games: GamesPath
        get(): GamesPath = games()
    override fun `as`(alias: String): TournamentCodes = TournamentCodes(DSL.name(alias), this)
    override fun `as`(alias: Name): TournamentCodes = TournamentCodes(alias, this)
    override fun `as`(alias: Table<*>): TournamentCodes = TournamentCodes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TournamentCodes = TournamentCodes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TournamentCodes = TournamentCodes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TournamentCodes = TournamentCodes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TournamentCodes = TournamentCodes(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TournamentCodes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TournamentCodes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TournamentCodes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TournamentCodes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TournamentCodes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TournamentCodes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TournamentCodes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TournamentCodes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TournamentCodes = where(DSL.notExists(select))
}
