/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import java.time.OffsetDateTime

import lblcs.tables.Events

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EventsRecord() : UpdatableRecordImpl<EventsRecord>(Events.EVENTS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var description: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var riotTournamentId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    open var startDate: OffsetDateTime?
        set(value): Unit = set(5, value)
        get(): OffsetDateTime? = get(5) as OffsetDateTime?

    open var endDate: OffsetDateTime?
        set(value): Unit = set(6, value)
        get(): OffsetDateTime? = get(6) as OffsetDateTime?

    open var status: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised EventsRecord
     */
    constructor(id: Int? = null, name: String? = null, description: String? = null, riotTournamentId: Int? = null, createdAt: OffsetDateTime? = null, startDate: OffsetDateTime? = null, endDate: OffsetDateTime? = null, status: String? = null): this() {
        this.id = id
        this.name = name
        this.description = description
        this.riotTournamentId = riotTournamentId
        this.createdAt = createdAt
        this.startDate = startDate
        this.endDate = endDate
        this.status = status
        resetChangedOnNotNull()
    }
}
