/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.tables.GamesResults

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GamesResultsRecord() : UpdatableRecordImpl<GamesResultsRecord>(GamesResults.GAMES_RESULTS) {

    open var gameId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var winner: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var loser: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised GamesResultsRecord
     */
    constructor(gameId: Int? = null, winner: Int? = null, loser: Int? = null): this() {
        this.gameId = gameId
        this.winner = winner
        this.loser = loser
        resetChangedOnNotNull()
    }
}
