/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.tables.Metadata

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MetadataRecord() : TableRecordImpl<MetadataRecord>(Metadata.METADATA) {

    open var riotProviderId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var logoBucketName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    /**
     * Create a detached, initialised MetadataRecord
     */
    constructor(riotProviderId: Int? = null, logoBucketName: String? = null): this() {
        this.riotProviderId = riotProviderId
        this.logoBucketName = logoBucketName
        resetChangedOnNotNull()
    }
}
