/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.enums.LolSide
import lblcs.tables.PlayerGameFacts

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerGameFactsRecord() : UpdatableRecordImpl<PlayerGameFactsRecord>(PlayerGameFacts.PLAYER_GAME_FACTS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var riotAccountId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var side: LolSide?
        set(value): Unit = set(2, value)
        get(): LolSide? = get(2) as LolSide?

    open var shortcode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var playerChampSelectId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var playerInventoriesId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var playerCombatsId: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var playerVisionId: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var playerPingsId: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var playerFarmingId: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PlayerGameFactsRecord
     */
    constructor(id: Int? = null, riotAccountId: Int? = null, side: LolSide? = null, shortcode: String? = null, playerChampSelectId: Int? = null, playerInventoriesId: Int? = null, playerCombatsId: Int? = null, playerVisionId: Int? = null, playerPingsId: Int? = null, playerFarmingId: Int? = null): this() {
        this.id = id
        this.riotAccountId = riotAccountId
        this.side = side
        this.shortcode = shortcode
        this.playerChampSelectId = playerChampSelectId
        this.playerInventoriesId = playerInventoriesId
        this.playerCombatsId = playerCombatsId
        this.playerVisionId = playerVisionId
        this.playerPingsId = playerPingsId
        this.playerFarmingId = playerFarmingId
        resetChangedOnNotNull()
    }
}
