/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.tables.Players

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayersRecord() : UpdatableRecordImpl<PlayersRecord>(Players.PLAYERS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var eventId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var teamId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PlayersRecord
     */
    constructor(id: Int? = null, name: String? = null, eventId: Int? = null, teamId: Int? = null): this() {
        this.id = id
        this.name = name
        this.eventId = eventId
        this.teamId = teamId
        resetChangedOnNotNull()
    }
}
