/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.tables.RiotAccounts

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class RiotAccountsRecord() : UpdatableRecordImpl<RiotAccountsRecord>(RiotAccounts.RIOT_ACCOUNTS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var riotPuuid: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised RiotAccountsRecord
     */
    constructor(id: Int? = null, riotPuuid: String? = null): this() {
        this.id = id
        this.riotPuuid = riotPuuid
        resetChangedOnNotNull()
    }
}
