/*
 * This file is generated by jOOQ.
 */
package lblcs.tables.records


import lblcs.tables.SeriesParticipants

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesParticipantsRecord() : UpdatableRecordImpl<SeriesParticipantsRecord>(SeriesParticipants.SERIES_PARTICIPANTS) {

    open var teamId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var seriesId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised SeriesParticipantsRecord
     */
    constructor(teamId: Int? = null, seriesId: Int? = null): this() {
        this.teamId = teamId
        this.seriesId = seriesId
        resetChangedOnNotNull()
    }
}
