/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.ApiKeys


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ApiKeysRecord() : UpdatableRecordImpl<ApiKeysRecord>(ApiKeys.API_KEYS) {

    open var key: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var createdAt: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised ApiKeysRecord
     */
    constructor(key: String? = null, userId: Int? = null, createdAt: Instant? = null): this() {
        this.key = key
        this.userId = userId
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
