/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.EventGroups


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class EventGroupsRecord() : UpdatableRecordImpl<EventGroupsRecord>(EventGroups.EVENT_GROUPS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var createdAt: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised EventGroupsRecord
     */
    constructor(id: Int? = null, name: String? = null, createdAt: Instant? = null): this() {
        this.id = id
        this.name = name
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
