/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.GameResults


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GameResultsRecord() : UpdatableRecordImpl<GameResultsRecord>(GameResults.GAME_RESULTS) {

    open var gameId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var winnerTeamId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var loserTeamId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised GameResultsRecord
     */
    constructor(gameId: Int? = null, winnerTeamId: Int? = null, loserTeamId: Int? = null): this() {
        this.gameId = gameId
        this.winnerTeamId = winnerTeamId
        this.loserTeamId = loserTeamId
        resetChangedOnNotNull()
    }
}
