/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.PersonalAccessTokens


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PersonalAccessTokensRecord() : UpdatableRecordImpl<PersonalAccessTokensRecord>(PersonalAccessTokens.PERSONAL_ACCESS_TOKENS) {

    open var token: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var userId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var scopes: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var expiresAt: Instant?
        set(value): Unit = set(4, value)
        get(): Instant? = get(4) as Instant?

    open var createdAt: Instant?
        set(value): Unit = set(5, value)
        get(): Instant? = get(5) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised PersonalAccessTokensRecord
     */
    constructor(token: String? = null, name: String? = null, userId: Int? = null, scopes: String? = null, expiresAt: Instant? = null, createdAt: Instant? = null): this() {
        this.token = token
        this.name = name
        this.userId = userId
        this.scopes = scopes
        this.expiresAt = expiresAt
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
