/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.PlayerInventories


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerInventoriesRecord() : UpdatableRecordImpl<PlayerInventoriesRecord>(PlayerInventories.PLAYER_INVENTORIES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var item0Id: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var item1Id: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var item2Id: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var item3Id: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var item4Id: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var item5Id: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var trinketId: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised PlayerInventoriesRecord
     */
    constructor(id: Int? = null, item0Id: Int? = null, item1Id: Int? = null, item2Id: Int? = null, item3Id: Int? = null, item4Id: Int? = null, item5Id: Int? = null, trinketId: Int? = null): this() {
        this.id = id
        this.item0Id = item0Id
        this.item1Id = item1Id
        this.item2Id = item2Id
        this.item3Id = item3Id
        this.item4Id = item4Id
        this.item5Id = item5Id
        this.trinketId = trinketId
        resetChangedOnNotNull()
    }
}
