/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.PlayerToTeams


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerToTeamsRecord() : UpdatableRecordImpl<PlayerToTeamsRecord>(PlayerToTeams.PLAYER_TO_TEAMS) {

    open var playerId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var teamId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var eventId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised PlayerToTeamsRecord
     */
    constructor(playerId: Int? = null, teamId: Int? = null, eventId: Int? = null): this() {
        this.playerId = playerId
        this.teamId = teamId
        this.eventId = eventId
        resetChangedOnNotNull()
    }
}
