/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record14
import org.jooq.Row14
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.PlayerChampSelects


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PlayerChampSelectsRecord() : UpdatableRecordImpl<PlayerChampSelectsRecord>(PlayerChampSelects.PLAYER_CHAMP_SELECTS), Record14<Int?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var championName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var championId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var summoner1Id: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var summoner2Id: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var keystoneRuneId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var primaryRune1Id: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open var primaryRune2Id: Int?
        set(value): Unit = set(7, value)
        get(): Int? = get(7) as Int?

    open var primaryRune3Id: Int?
        set(value): Unit = set(8, value)
        get(): Int? = get(8) as Int?

    open var secondaryRune1Id: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    open var secondaryRune2Id: Int?
        set(value): Unit = set(10, value)
        get(): Int? = get(10) as Int?

    open var statshard1Id: Int?
        set(value): Unit = set(11, value)
        get(): Int? = get(11) as Int?

    open var statshard2Id: Int?
        set(value): Unit = set(12, value)
        get(): Int? = get(12) as Int?

    open var statshard3Id: Int?
        set(value): Unit = set(13, value)
        get(): Int? = get(13) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row14<Int?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.fieldsRow() as Row14<Int?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun valuesRow(): Row14<Int?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?> = super.valuesRow() as Row14<Int?, String?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?, Int?>
    override fun field1(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.ID
    override fun field2(): Field<String?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.CHAMPION_NAME
    override fun field3(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.CHAMPION_ID
    override fun field4(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.SUMMONER1_ID
    override fun field5(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.SUMMONER2_ID
    override fun field6(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.KEYSTONE_RUNE_ID
    override fun field7(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.PRIMARY_RUNE1_ID
    override fun field8(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.PRIMARY_RUNE2_ID
    override fun field9(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.PRIMARY_RUNE3_ID
    override fun field10(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.SECONDARY_RUNE1_ID
    override fun field11(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.SECONDARY_RUNE2_ID
    override fun field12(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.STATSHARD1_ID
    override fun field13(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.STATSHARD2_ID
    override fun field14(): Field<Int?> = PlayerChampSelects.PLAYER_CHAMP_SELECTS.STATSHARD3_ID
    override fun component1(): Int? = id
    override fun component2(): String? = championName
    override fun component3(): Int? = championId
    override fun component4(): Int? = summoner1Id
    override fun component5(): Int? = summoner2Id
    override fun component6(): Int? = keystoneRuneId
    override fun component7(): Int? = primaryRune1Id
    override fun component8(): Int? = primaryRune2Id
    override fun component9(): Int? = primaryRune3Id
    override fun component10(): Int? = secondaryRune1Id
    override fun component11(): Int? = secondaryRune2Id
    override fun component12(): Int? = statshard1Id
    override fun component13(): Int? = statshard2Id
    override fun component14(): Int? = statshard3Id
    override fun value1(): Int? = id
    override fun value2(): String? = championName
    override fun value3(): Int? = championId
    override fun value4(): Int? = summoner1Id
    override fun value5(): Int? = summoner2Id
    override fun value6(): Int? = keystoneRuneId
    override fun value7(): Int? = primaryRune1Id
    override fun value8(): Int? = primaryRune2Id
    override fun value9(): Int? = primaryRune3Id
    override fun value10(): Int? = secondaryRune1Id
    override fun value11(): Int? = secondaryRune2Id
    override fun value12(): Int? = statshard1Id
    override fun value13(): Int? = statshard2Id
    override fun value14(): Int? = statshard3Id

    override fun value1(value: Int?): PlayerChampSelectsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: String?): PlayerChampSelectsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): PlayerChampSelectsRecord {
        set(2, value)
        return this
    }

    override fun value4(value: Int?): PlayerChampSelectsRecord {
        set(3, value)
        return this
    }

    override fun value5(value: Int?): PlayerChampSelectsRecord {
        set(4, value)
        return this
    }

    override fun value6(value: Int?): PlayerChampSelectsRecord {
        set(5, value)
        return this
    }

    override fun value7(value: Int?): PlayerChampSelectsRecord {
        set(6, value)
        return this
    }

    override fun value8(value: Int?): PlayerChampSelectsRecord {
        set(7, value)
        return this
    }

    override fun value9(value: Int?): PlayerChampSelectsRecord {
        set(8, value)
        return this
    }

    override fun value10(value: Int?): PlayerChampSelectsRecord {
        set(9, value)
        return this
    }

    override fun value11(value: Int?): PlayerChampSelectsRecord {
        set(10, value)
        return this
    }

    override fun value12(value: Int?): PlayerChampSelectsRecord {
        set(11, value)
        return this
    }

    override fun value13(value: Int?): PlayerChampSelectsRecord {
        set(12, value)
        return this
    }

    override fun value14(value: Int?): PlayerChampSelectsRecord {
        set(13, value)
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: Int?, value4: Int?, value5: Int?, value6: Int?, value7: Int?, value8: Int?, value9: Int?, value10: Int?, value11: Int?, value12: Int?, value13: Int?, value14: Int?): PlayerChampSelectsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        this.value9(value9)
        this.value10(value10)
        this.value11(value11)
        this.value12(value12)
        this.value13(value13)
        this.value14(value14)
        return this
    }

    /**
     * Create a detached, initialised PlayerChampSelectsRecord
     */
    constructor(id: Int? = null, championName: String? = null, championId: Int? = null, summoner1Id: Int? = null, summoner2Id: Int? = null, keystoneRuneId: Int? = null, primaryRune1Id: Int? = null, primaryRune2Id: Int? = null, primaryRune3Id: Int? = null, secondaryRune1Id: Int? = null, secondaryRune2Id: Int? = null, statshard1Id: Int? = null, statshard2Id: Int? = null, statshard3Id: Int? = null): this() {
        this.id = id
        this.championName = championName
        this.championId = championId
        this.summoner1Id = summoner1Id
        this.summoner2Id = summoner2Id
        this.keystoneRuneId = keystoneRuneId
        this.primaryRune1Id = primaryRune1Id
        this.primaryRune2Id = primaryRune2Id
        this.primaryRune3Id = primaryRune3Id
        this.secondaryRune1Id = secondaryRune1Id
        this.secondaryRune2Id = secondaryRune2Id
        this.statshard1Id = statshard1Id
        this.statshard2Id = statshard2Id
        this.statshard3Id = statshard3Id
        resetChangedOnNotNull()
    }
}
