/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.SeriesResults


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesResultsRecord() : UpdatableRecordImpl<SeriesResultsRecord>(SeriesResults.SERIES_RESULTS), Record3<Int?, Int?, Int?> {

    open var seriesId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var winnerTeamId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var loserTeamId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Int?, Int?, Int?> = super.fieldsRow() as Row3<Int?, Int?, Int?>
    override fun valuesRow(): Row3<Int?, Int?, Int?> = super.valuesRow() as Row3<Int?, Int?, Int?>
    override fun field1(): Field<Int?> = SeriesResults.SERIES_RESULTS.SERIES_ID
    override fun field2(): Field<Int?> = SeriesResults.SERIES_RESULTS.WINNER_TEAM_ID
    override fun field3(): Field<Int?> = SeriesResults.SERIES_RESULTS.LOSER_TEAM_ID
    override fun component1(): Int? = seriesId
    override fun component2(): Int? = winnerTeamId
    override fun component3(): Int? = loserTeamId
    override fun value1(): Int? = seriesId
    override fun value2(): Int? = winnerTeamId
    override fun value3(): Int? = loserTeamId

    override fun value1(value: Int?): SeriesResultsRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): SeriesResultsRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): SeriesResultsRecord {
        set(2, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?): SeriesResultsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised SeriesResultsRecord
     */
    constructor(seriesId: Int? = null, winnerTeamId: Int? = null, loserTeamId: Int? = null): this() {
        this.seriesId = seriesId
        this.winnerTeamId = winnerTeamId
        this.loserTeamId = loserTeamId
        resetChangedOnNotNull()
    }
}
