/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.Series


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesRecord() : UpdatableRecordImpl<SeriesRecord>(Series.SERIES), Record3<Int?, Int?, Int?> {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var eventId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var gamesToWin: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row3<Int?, Int?, Int?> = super.fieldsRow() as Row3<Int?, Int?, Int?>
    override fun valuesRow(): Row3<Int?, Int?, Int?> = super.valuesRow() as Row3<Int?, Int?, Int?>
    override fun field1(): Field<Int?> = Series.SERIES.ID
    override fun field2(): Field<Int?> = Series.SERIES.EVENT_ID
    override fun field3(): Field<Int?> = Series.SERIES.GAMES_TO_WIN
    override fun component1(): Int? = id
    override fun component2(): Int? = eventId
    override fun component3(): Int? = gamesToWin
    override fun value1(): Int? = id
    override fun value2(): Int? = eventId
    override fun value3(): Int? = gamesToWin

    override fun value1(value: Int?): SeriesRecord {
        set(0, value)
        return this
    }

    override fun value2(value: Int?): SeriesRecord {
        set(1, value)
        return this
    }

    override fun value3(value: Int?): SeriesRecord {
        set(2, value)
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: Int?): SeriesRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised SeriesRecord
     */
    constructor(id: Int? = null, eventId: Int? = null, gamesToWin: Int? = null): this() {
        this.id = id
        this.eventId = eventId
        this.gamesToWin = gamesToWin
        resetChangedOnNotNull()
    }
}
