/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.Series


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SeriesRecord() : UpdatableRecordImpl<SeriesRecord>(Series.SERIES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var eventId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var gamesToWin: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised SeriesRecord
     */
    constructor(id: Int? = null, eventId: Int? = null, gamesToWin: Int? = null): this() {
        this.id = id
        this.eventId = eventId
        this.gamesToWin = gamesToWin
        resetChangedOnNotNull()
    }
}
