/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.time.Instant
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.Sessions


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class SessionsRecord() : UpdatableRecordImpl<SessionsRecord>(Sessions.SESSIONS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var userId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var expiresAt: Instant?
        set(value): Unit = set(2, value)
        get(): Instant? = get(2) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised SessionsRecord
     */
    constructor(id: UUID? = null, userId: Int? = null, expiresAt: Instant? = null): this() {
        this.id = id
        this.userId = userId
        this.expiresAt = expiresAt
        resetChangedOnNotNull()
    }
}
