/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.Teams


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamsRecord() : UpdatableRecordImpl<TeamsRecord>(Teams.TEAMS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var eventId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var logoKey: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised TeamsRecord
     */
    constructor(id: Int? = null, name: String? = null, eventId: Int? = null, logoKey: UUID? = null): this() {
        this.id = id
        this.name = name
        this.eventId = eventId
        this.logoKey = logoKey
        resetChangedOnNotNull()
    }
}
