/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.TeamToSeries


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TeamToSeriesRecord() : UpdatableRecordImpl<TeamToSeriesRecord>(TeamToSeries.TEAM_TO_SERIES) {

    open var teamId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var seriesId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised TeamToSeriesRecord
     */
    constructor(teamId: Int? = null, seriesId: Int? = null): this() {
        this.teamId = teamId
        this.seriesId = seriesId
        resetChangedOnNotNull()
    }
}
