/*
 * This file is generated by jOOQ.
 */
package org.jooq.storage.tables.records


import java.time.Instant

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import org.jooq.storage.tables.TournamentCodes


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TournamentCodesRecord() : UpdatableRecordImpl<TournamentCodesRecord>(TournamentCodes.TOURNAMENT_CODES) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var shortcode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var blueTeamId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var redTeamId: Int?
        set(value): Unit = set(3, value)
        get(): Int? = get(3) as Int?

    open var seriesId: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    open var createdAt: Instant?
        set(value): Unit = set(5, value)
        get(): Instant? = get(5) as Instant?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised TournamentCodesRecord
     */
    constructor(id: Int? = null, shortcode: String? = null, blueTeamId: Int? = null, redTeamId: Int? = null, seriesId: Int? = null, createdAt: Instant? = null): this() {
        this.id = id
        this.shortcode = shortcode
        this.blueTeamId = blueTeamId
        this.redTeamId = redTeamId
        this.seriesId = seriesId
        this.createdAt = createdAt
        resetChangedOnNotNull()
    }
}
