name: Prevents changes to locked migrations.

on:
  push:
    branches:
      - main
      - release/*

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
    - name: Prevent changes to LOCKED migrations.
      uses: xalvarez/prevent-file-change-action@v2
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        pattern: src/migrations/sql/*__LOCKED\.sql
        allowNewFiles: true
