name: Run tests on PRs

on:
  pull_request:
    types: 
      - opened
    branches: 
      - 'main'
  push:
    branches:
      - 'dev/**'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Utilizes Gradle cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test project
        run: ./gradlew test

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Utilizes Gradle cache
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test project
        run: ./gradlew itest