name: Run Lint and Static Code Analysis

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v4

      - name: Run ktlintCheck and detekt
        run: ./gradlew ktlintCheck detekt